### ISSUE TITLE
Add ability to document BEM

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sassdoc#18]
From @alademann in #15:

> Modular (BEM/OOCSS) Hierarchy

> * `@module` - define a file as a module.
> 
>     * `@base` - define a class/id as a "base" class/id for a module.
>         * `@element` - define a class/id as a "element" class/id for a "base" class/id
>         * `@modifier {type}` - define a class/id as a "modifier" class/id for a "base" or "element" class/id
>             * The `{type}` would be "open-ended", but would be something like variant or state, for example.
> * `@depends` - similar to `@requires` - except this would create a link to an external `@module` (or even some JS) that is not implied via the declared `@base` / `@element` / `@modifier` syntax.
>     * allow multiple via comma-separated list - or multiple `@depends` lines (see $panel var example below)?
> * `@extends` - similar to `@depends`, but this type of element would automatically extend a dependency instead of implying that the other module/component had to be used/included separately.

From @valeriangalliat in #15:

> I like the idea of documenting BEM classes.

> Like the name and value for variables, we can also get the class name by looking the line after the docblock, it's redundant to add it after the annotation. But maybe it can be tricky to find it in the selector for more complex cases?

From me in #15:

> Okay, I like that. Although I don't think it's possible to do that with regular expressions right now so until we have a dedicated parser, this probably won't work.

> I have hard time seeing the difference between @depends and @requires. As far as possible, I'd like to keep only one, unless both are serving strictly different purposes.

**Comment by bjudson** [comment]
I would find the ability to document selectors really valuable. I don't think it should be specific to any CSS style (BEM/SMACCS/etc), but just allow using the existing comment syntax to document selectors. Maybe add `@extends` as mentioned above to reference the selector of the base module, which is a very common pattern. We can already use `@group` to label selectors as modules.

**Comment by HugoGiraudel** [comment]
I am going to close this one. I don't want that for now. I'll open it again we were all out of ideas for Sass documentation.

**Comment by wintercounter** [comment]
Maybe just a simplier way?

```scss
.list {
  /// @group lists
  /// @selector/alias/etc .list--square (only where using interpolation or it cannot be easily determined from the selector)
  /// Description of my selector
  &--square {
    list-style-type: square;
  }
}
```

I also would like to see the same for map values for example.

It would give us a free way to document anything and group them so it can be used for specific cases also.

**Comment by HugoGiraudel** [comment]
> I also would like to see the same for map values for example.

We already have `@prop` to document map key/value pairs.

**Comment by wintercounter** [comment]
True, sorry for that :) Anyway, some freely used group-able annotation for any circumstance would be awesome.

**Comment by ncoden** [comment]
poke @HugoGiraudel

I think lot of good ideas have been given in this issue. Why not re-opening it now ?

**Comment by pascalduez** [comment]
> Why not re-opening it now ?

Mostly because SassDoc's core is aiming at staying small and focused, and as much as we love BEM it's still a very specific usage of CSS that not all projects will benefits from.
So we tend to delegate all that kind of needs to the theme layer. 

In such case, creating [custom annotations](http://sassdoc.com/extending-sassdoc/).

Also the default theme won't document CSS classes.

**Comment by mattdrose** [comment]
Why make it BEM specific? If you do decide to document CSS, you should make it decoupled from a class naming convention.

Oooh. Didn't know there were annotations! Will give them a try 😍👍. Thanks
