### ISSUE TITLE
Add ability to group multiple vars

### ISSUE THREAD

**Issue by markgoodyear** [SassDoc/sassdoc#195]
Having the ability to group a block of vars would be quite handy when documenting related vars, helping reduced the amount of comments required for related items.

Here is an example:

``` scss
/**
 * Helper classes for adding/removing spacing.
 * @group Helpers
 * @block spacing-helpers
 */
$spacing-margins:          false !default;
$spacing-margins--double:  false !default;
$spacing-margins--half:    false !default;
$spacing-margins--zero:    false !default;
$spacing-paddings:         false !default;
$spacing-paddings--double: false !default;
$spacing-paddings--half:   false !default;
$spacing-paddings--zero:   false !default;
```

By having `@block` it'd group everything that is in the block, and perhaps stop the group when a new line is present. `block` is a loose term as I can't think of anything that may be better suited at the moment.

**Comment by vuhrmeister** [comment]
I just used SassDoc the first time in a project and I really feel the need for grouping multiple variables.
Especially for defining colors or font-sizes. I want to have them all documented, but I don't need every single font size separated as this is just repeating information.

**Comment by HugoGiraudel** [comment]
My suggestion would be to use file-level annotations then.

**Comment by vuhrmeister** [comment]
Well, but would that really be an alternative? I mean I have a file-level annotation "@group typography". 
If I would create a separate file for everything I want to group, then I mess up the navigation.
Also with just file-level annotation I wouldn't have any automation since I would need to add markdown for documenting all variables (which are then also not listed in the navigation).

**Comment by shtev21** [comment]
I still think this would be very beneficial in terms of documentation. The end use is that docs will serve as a quick primer on what variables are in use for the project.

My specific use case is that I use BEM style variable names and will have multiple that all serve the same purpose (all are colors) and they should all be documented together.

As a rudimentary example:

```scss
$cl__light--alpha: #0066cc;
$cl__light--beta: #91b252;
$cl__action--alpha: #0066cc;
$cl__action--beta: lighten($cl__action--alpha, 10%);
```
Should ideally all be documented together, both at a group level, but also as individual presentations within a larger cluster.

My solution to this would be using the keywords `@cluster` and `(` to denote sub-groups. Something like:

```scss

/// This is the master comment for the cluster
/// @group colors
/// @cluster

/// @cluster-item color-variable
$cl__light--alpha: #0066cc;

/// @cluster-item color-variable
$cl__light--beta: #91b252;

/// @cluster-item color-variable
$cl__action--alpha: #0066cc;

/// @cluster-item color-variable
$cl__action--beta: lighten($cl__action--alpha, 10%);
```

Cluster names could then also be mapped similarly to groups in the config file, and they will be presented as a single code example item within the output.

![image](https://user-images.githubusercontent.com/2514805/47303572-2dc34380-d61c-11e8-8d52-83e67da963dc.png)
