### ISSUE TITLE
Add ability to generate snippets

### ISSUE THREAD

**Issue by arleym** [SassDoc/sassdoc#204]
Once the ability to generate documentation markup is possible, it would be an amazing feature to build auto-generating snippets (In my example below I'm going to reference Sublime Text snippet notation, but other editors and IDEs have a similar feature, with different markup). 

A Sublime Text snippet is a block of markup that can be generated in your document by typing a "trigger" and hitting `tab` (this is not unlike creating your own Emmet shortcut). In [this example](https://gist.github.com/arleym/894315b9f8a7fb84a8f9) hitting `tab` after typing "accordion" will generate some generic accordion markup. 

Using snippets removes some guess work: it makes for faster development, more consistent code, and can help catch some code attributes that are often overlooked like schema.org and ARIA attributes.

- A build setting would be required to configure what kind of file gets built (based on the editor the snippet is for)
- The Sass comment block for snippets would include the trigger key, and markup
- The snippet reference would get included in the documentation
- It would be awesome if there was an automatic snippet like `sass-snippets` that would reference a comment block of all available snippets!
- Once the docs and snippet files are all generated the developer would either need to move the snippet files, or better yet have a symlink on their system to the snippet build directory. 

This may be a bit scope-creepy and not entirely about documenting Sass; but becomes about documenting the ways to build the HTML the Sass is styling. It's so integral to documentation that I think it belongs with a tool like this rather than a stand-alone.

**Comment by HugoGiraudel** [comment]
Not on our side, I’m closing. :)

**Comment by jsit** [comment]
In case anybody gets here via Google (like I did), I created a tool on GitHub and npm that can do this: https://github.com/jsit/sassdoc-to-snippets

Please leave feedback if you like!
