### ISSUE TITLE
Add ability to use file exclusion patterns or glob expressions

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#228]
On IRC @jsit asked whether SassDoc supports files exclusions patterns.
I kinda like the idea, and we could push things even further with supporting glob expressions ?
Since some major refactor will be engaged in `file.js` anyway. See #217 + upcoming issue.

But somehow it's raising some questions:
If you don't want files or items to show up in your docs, just don't document them... 
Or use standard inline comments `//`.
One could also use a poster comment per file with an `@private`.

Does it makes sense ?
How would we implement this ?

**Comment by jsit** [comment]
Where is this supposed to happen? In the config file? Should something like this work in theory?:

```json
"exclude": [
  "vendor",
  "../scss/vendor/",
  "../scss/vendor/**",
  "../scss/vendor/**/*"
],
```

I can't seem to get this working.

**Comment by pascalduez** [comment]
Yes, it's something you can use in the config file.

Could you show us the include patterns or src and give a bit more insight ?

**Comment by jsit** [comment]
My mistake, I had a bad glob string. Thanks!
