### ISSUE TITLE
Add ability to describe an introduction text

### ISSUE THREAD

**Issue by Undistraction** [SassDoc/sassdoc#256]
It would be great to be able to add an Introduction to the documentation. just something to sit above the generated docs in the main column (in the default theme). 

If I have a README outlining how the library should be used and full of examples, it would seem to me this should be something that I can include into the docs as an introduction. I'd love to be able to just direct to the Sassdoc from the README, but pure docs without context mean I'm going to end up boiling a lot of the docs down into the README. Being able to consolidate intro and docs would make both docs and introduction stronger.

This could be expanded to allow links from the intro to the relevant docs (perhaps just parsing out known entities from the text and adding links automagically).

**Comment by HugoGiraudel** [comment]
Regarding this (part of 2.1), there is something I don't like much. When taking an actual `package.json` file as a `package`, there is absolutely no way that the `description` ends up being a path to a Markdown file. This is not how *description* works as per the package spec or whatever you want to call this.

**Comment by HugoGiraudel** [comment]
What would be the best way to tackle this one? I'm thinking of:

* Add a `description` (or `fullDescription` or whatever) key to the configuration
* If it is a string, parses it as Markdown
* if it is a path, get content and parses it as Markdown

Thoughts @SassDoc/owners?

**Comment by pascalduez** [comment]
> Add a description (or fullDescription or whatever) key to the configuration
    If it is a string, parses it as Markdown
    if it is a path, get content and parses it as Markdown

Looks perfect. Exactly what I had in mind.

**Comment by pascalduez** [comment]
It's a theme feature.
Moved to SassDoc/sassdoc-theme-default#66
