### ISSUE TITLE
Consider Style-guide Generation / Integration

### ISSUE THREAD

**Issue by Undistraction** [SassDoc/sassdoc#268]
I appreciate this is something big and I'm sure you've all seen this before, but I find the lack of support for documenting classes with Sassdoc  leaves a bit of a hole. [Hologram](http://trulia.github.io/hologram/) seems to fill that hole nicely, but I don't really want two distinct sets of doc-comments in a project. 

I was wondering if you had considered looking at integration or your own take on this?

**Comment by eikeco** [comment]
+1 for this. I only realised it didn't support this long after I installed it.
