### ISSUE TITLE
Full stream ahead

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#287]
We already did quite a great amount of work around streams in the `2.0.0` refactoring.
I think we could push things even further and allow some sort of full streams support. Read pipelines.

As for Grunt and Broccoli it's all file based, so the main [sassdoc method is enough](https://github.com/SassDoc/grunt-sassdoc/blob/develop/tasks/sassdoc.js#L55). We are basically replicating the `cli` behavior here. But the <del>revolution</del> future will <del>not</del> be [streamed](https://cowboy.github.io/state-of-grunt-fe-summit-2014-talk/#60).

Gulp instead, provides its own stream of Vinyl files. One of the main motivation about the refactor and API decoupling was to be able to leverage this. So basically in the Gulp plugin We only need the [parsing part](https://github.com/SassDoc/sassdoc/blob/develop/src/sassdoc.js#L85).
*I think we failed a bit at truly decoupling the different steps.* 
Right now that means we need to replicate/clone most of the code from [`sassdoc.js`](https://github.com/SassDoc/sassdoc/blob/develop/src/sassdoc.js) in the Gulp plugin to be able to only pipe the parser, redo all the promises chain, the refresh, the theme, the error handling... plus the config stuff from `cli`. 
*That feels utterly wrong*

**Proposed solution**
Allow streams piping in SassDoc, and deprecate the Gulp plugin. Instead pipe directly sassdoc.
That's an [underlying guideline](https://medium.com/@sogko/gulp-browserify-the-gulp-y-way-bb359b3f9623) in the Gulp world also, *don't build plugins just for the sake of it*.

Something similar to what [browserify does](https://github.com/substack/node-browserify#api-example).

That way we would maybe not need to expose [the inner guts of SassDoc](https://github.com/SassDoc/sassdoc/blob/develop/src/sassdoc.js#L109) which are clumsy to use in a decoupled manner at the moment.

So at the end using SassDoc with Gulp would look like:
```js
var gulp = require('gulp');
var sassdoc = require('sassdoc');

// Maybe we need something like ?
var sassdoc = require('sassdoc').stream;

gulp.task('sassdoc', function () {
  return gulp.src('src/**/*.scss')
    .pipe(sassdoc({
        'dest': 'path/to/docs'
    }));
});
```
And we pass files through so SassDoc can be piped in a Sass workflow
```js
var gulp = require('gulp');
var sassdoc = require('sassdoc');
var sass = require('gulp-sass');

gulp.task('sassy', function () {
  return gulp.src('src/**/*.scss')
    .pipe(sassdoc({
        'dest': 'path/to/docs'
    }))
    .pipe(sass())
    .pipe(gulp.dest('./css'));
});
```
At some point maybe Themeleon will also allow transform streams ?
```js
var gulp = require('gulp');
var sassdoc = require('sassdoc');

gulp.task('sassdoc', function () {
  return gulp.src('src/**/*.scss')
    .pipe(sassdoc())
    .pipe(gulp.dest('path/to/docs'));
});
```

**Discussion:** Thoughts, ideas ?

**Satus:** I'm currently on it, trying to allow this.

**Comment by HugoGiraudel** [comment]
Current status @pascalduez?

**Comment by pascalduez** [comment]
First pass on the [`stream-api` branch](https://github.com/SassDoc/sassdoc/compare/develop...stream-api) 
Working on a cleanup, plus landing support for `stdin` input.
