### ISSUE TITLE
SassDocMeister

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sassdoc#295]
@valeriangalliat had an interesting idea this morning about a *SassDocMeister* project. The idea is the same as [SassMeister](http://sassmeister.com): you put code on the left side, you got an output on the right side.

Now, the idea would be to put Sass code on the left, and have the data tree representation generated by SassDoc on the right. This would be great for us to test our features, as well as for theme builders to test things.

We could imagine a couple of options, like the one from the configuration file, the ability to run filters (Markdown and such), and so on.

Let's open the discussion.

**Comment by valeriangalliat** [comment]
https://github.com/SassDoc/sassdocmeister
http://sassdoc.com/sassdocmeister/

**Comment by FWeinb** [comment]
:+1: :fireworks:
