### ISSUE TITLE
Add ability to override name with `@name`

### ISSUE THREAD

**Issue by davidkpiano** [SassDoc/sassdoc#296]
According to the docs:

> Name of the documented item is self parsed, hence `@name` doesn’t exist.

This makes perfect sense, but in the case where I want to document something that has an interpolated value, it's a little disappointing. For example, if I'm trying to document `%foo-#{$bar} {...}` then I will get the Sassdoc entry as the placeholder **foo-**.

I understand it might be asking a bit much for Sassdoc to do variable interpolation, so if I could add something custom like `@name foo-[value of bar]` to be more descriptive about the component, that would be great.

**Comment by pascalduez** [comment]
#358 merged.
