### ISSUE TITLE
Always output into its own directory

### ISSUE THREAD

**Issue by FWeinb** [SassDoc/sassdoc#302]
Moving issues from SassDoc/gulp-sassdoc#8

Quote @ben-eb
>```
.
├── README.md
├── assets
│   ├── css
│   └── js
└── sassdoc
    ├── assets
    └── index.html
```

>This is a clearer, more intuitive way of running the software. Not only do the `force` and `interactive` operations become obsolete, but we tell the user that their documentation *by default* creates a folder for itself, and subsequent runs will update that folder.


And @HugoGiraudel :
> If we are willing to do this, make the folder name customisable, and chose a secure default (i.e. not `sassdoc`). 


[JsDoc](https://github.com/jsdoc3/jsdoc#running-jsdoc-with-nodejs) is doing it this way too.

**Comment by HugoGiraudel** [comment]
@SassDoc/owners Who takes this?

**Comment by valeriangalliat** [comment]
I can, but probably not before next week.

**Comment by pascalduez** [comment]
> I can, but probably not before next week.

Would be nice if @valeriangalliat could tackle this, and I would prefer to land the stream refacto before, so I don't have to rebase/redo that another time :) It's already been too much sliced till now.

**Comment by HugoGiraudel** [comment]
Alright. @valeriangalliat, your move.

**Comment by valeriangalliat** [comment]
Why not `sassdoc` as default? There's little chance such a folder already exists, right?
Otherwise, we can name it `out` like JSDoc maybe?

**Comment by FWeinb** [comment]
I am all for `sassdoc`. But what we want is  always append the folder sassdoc. Even if the user has supplied a path.

**Comment by valeriangalliat** [comment]
From what I understood, there's no more `dest` argument, it's rather an option defaulting to `out`.

So `sassdoc src` will create `out` in the CWD, and `sassdoc src --dest doc` will put the documentation in `doc`.

**Comment by HugoGiraudel** [comment]
Sounds  good. Go for `sassdoc` as a default.

**Comment by valeriangalliat** [comment]
Okay, I just ammended the PRs to replace `out` with `sassdoc`.
