### ISSUE TITLE
Cannot get SassDoc's to generate anything but default index.html

### ISSUE THREAD

**Issue by jsheffers** [SassDoc/sassdoc#309]
I have tried SassDocs two different ways to no avail.

### The first - Command line tool ###
Simply using the command line tool to compile my documentation.  It creates an assets folder and an index.html file, but it just says "Seems like nothing has been documented yet."  It doesn't matter how many comments I put in my Sass the index.html file never changes.   If I duplicate a comment I get an error saying I can't have duplicate comments, so it must be parsing my file.

### The second - Gulp ###
Having the same issues here.  The assets folder and index.html generate, but I never get any actual output.

Any ideas?  This could just be my lack of knowledge, but I can't seem to figure this out.

**Comment by jsheffers** [comment]
Ahh, I knew it was user error.  So there is no way to document a whole selector, just the item's you mentioned above?

**Comment by valeriangalliat** [comment]
Yep, @HugoGiraudel can explaint it way better than me, but SassDoc is only for documenting Sass/SCSS code, not CSS. That is, you can document variables, mixins, functions and placeholders, but not CSS selectors.

There's been a related issue about [documenting BEM classes](https://github.com/SassDoc/sassdoc/issues/18), but currently SassDoc is not taking the path to be a CSSDoc.

**Comment by HugoGiraudel** [comment]
> Yep, @HugoGiraudel can explain it way better than me,

I don't. You did one hell of a job. :)

**Comment by jsheffers** [comment]
Great, thanks for the explanation.  Thanks guys!

**Comment by Yugloocamai** [comment]
I know this is super old, but I'm having the same issue, except that I'm commenting actual sass lines, and still, nothing but the default page "Seems like nothing has been documented yet!" is produced.

**Comment by pascalduez** [comment]
@Yugloocamai There's no way we can help you with so few informations.  
Best with reporting issues is providing verbose output and descriptions as well as all parameters and context. Also bare reduced repository reproducing the issue.
