### ISSUE TITLE
partial files

### ISSUE THREAD

**Issue by R3l4x3** [SassDoc/sassdoc#310]
Is there a way to parse partial files too? At the moment my doc only include 1 .scss file with one variable but in this file you find this variable and 2 @import. But these files are ignored.

**Comment by pascalduez** [comment]
SassDoc will parse all `.scss` files that are childs of your source folder: `src`. Partials files included.
Could you provide a bit more insights to help us help you ?

**Comment by R3l4x3** [comment]
ok, here a screen of our file structure:
![file-structure](https://cloud.githubusercontent.com/assets/5042379/5643706/e6a46280-965b-11e4-95d5-a7827049523c.png)

The content of styles.scss:
```scss
$sprites-layout: smart;
//@import "../sprites/*.png";

@import "framework";
@import "project";
```

_framework.scss & _project.scss include more @import

And this is the SassDoc after I used the following command ```sassdoc . ../test/ -c .sassdocrc --verbose``` 
![output](https://cloud.githubusercontent.com/assets/5042379/5643763/92048b0a-965c-11e4-8f09-7d4d2b751c8f.png)

Do you need more information?

**Comment by pascalduez** [comment]
SassDoc will not care about `@import`. But since `_framework.scss` `_project.scss` are on the same level as `styles.scss` they should be parsed too. If I understand well, the CWD your in is `css` ?
Do those files have SassDoc comments in ?

**Comment by R3l4x3** [comment]
Oh, maybe I interpret the SassDoc slightly wrong. I thought I could pass a comment on top of every file to  describe a file and its usage. If I get the SassDoc right I can describe variables, mixins and functions "only"?
Yes, the CWD is ```css```.

**Comment by pascalduez** [comment]
You have file level annotations, that will apply to every elements in the file (unless overridden).
http://sassdoc.com/file-level-annotations
But this means having elements in the file...

SassDoc supports variables, placeholders, functions, mixins.

**Comment by pascalduez** [comment]
So if you want to keep your docs structure similar to your files, you have to use a mixture of file level annotations and groups:

_framework.scss
```scss
////
//// @group framework
////

/// Whatsoever
@function foo() {}
``` 

_project.scss
```scss
////
//// @group project
////

/// Whatever
@function bar() {}
``` 

in your `.sassdocrc`: 

```js
groups: {
  "undefined": "General",
  "framework": "Framework related stuff title",
  "project": "Project related stuff title"
}
```

**Comment by R3l4x3** [comment]
Ok, thank you for your help, @pascalduez !

But it seems that I've a new problem or something I don't either:

This is a partial file for testing purposes
```scss
/**
 * font.scss
 *
 * @author   Sebastian
 **/


$test: 12 !default;

/**
 * font-size
 *
 * @author   Sebastian
 */
@mixin font-size($px: $test) {
    font-size: $px + px;
    font-size: ($px / 10) + rem;
}
```

This is the SassDoc CLI Output:
```
$ sassdoc default/skin/css default/skin/test/ -c default/skin/css/.sassdocrc --verbose
[?] Destination folder will be wiped out. Are you sure you want to proceed? [y/N] y
[2015-01-07 11:48:08] Folder `default/skin/test/` successfully generated.
[2015-01-07 11:48:08] File `default/skin/css/.sassdocrc` is not a `.scss` file. Omitted.
[2015-01-07 11:48:08] File `default/skin/css/styles.css` is not a `.scss` file. Omitted.
[2015-01-07 11:48:08] Folder `default/skin/css` successfully parsed.
[2015-01-07 11:48:08] Theme `default` successfully rendered.
[2015-01-07 11:48:08] Process over. Everything okay!
```

And this is my Doc-Output:
![magento_bootstrap_boilerplate_-_v0_1](https://cloud.githubusercontent.com/assets/5042379/5644409/6abe8602-9663-11e4-9ab2-024ba0cc0b4e.png)

It strikes me that there:
- is no parameter in the mixin brackets
- there is no variable $test

Where is my mistake?

**Comment by HugoGiraudel** [comment]
You have to declare your parameters with `@param`.

Try removing empty lines between the comment and your variable declaration.

**Comment by pascalduez** [comment]
```scss
$test: 12 !default;
```

Needs to have a comment to appear in the doc

```scss
/**
 * A variable
 */
$test: 12 !default;
```

**Comment by R3l4x3** [comment]
Okay, I think I get it now. Thank you guys for your help!
