### ISSUE TITLE
Consider adding a debug option

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#311]
After seeing issues like #309 #310 and obviously other ones in the past, we could benefit from adding a new `-d --debug` options. 
This would not produce the final documentation but output useful information on the current environment. Either to `stdout` or in a `sassdoc-debug.log`.

- [x] SassDoc version
- [x] Node.js version
- [x] npm version
- [x] platform
- [x] CLI location (either global or local)
- [x] If CLI command run and options
- [x] is a plugin used (Grunt, Gulp, ...)
- [x] source path
- [x] destination path
- [x] CWD (maybe not useful for plugins?)
- [x] environment (implies config)
- [x] data

**Comment by HugoGiraudel** [comment]
I like that.

**Comment by valeriangalliat** [comment]
:+1:

Added CWD in your list.

**Comment by valeriangalliat** [comment]
All okay to replace `--debug` by `-vv`?

**Comment by valeriangalliat** [comment]
> is a plugin used (Grunt, Gulp, ...)

I don't understand. If `--debug` is a CLI option, plugins are not concerned, right?

**Comment by pascalduez** [comment]
> I don't understand. If --debug is a CLI option, plugins are not concerned, right?

Good call... Would be interesting to be able to debug from plugins as well. Which means it should be a config option as well.

**Comment by valeriangalliat** [comment]
That's what I had in mind. I'll log some CLI-specific stuff in `cli.js` and the rest in `sassdoc.js`, and `debug` will be a config option (but ideally this config option should be settable from Grunt/Gulp command, like `grunt --sassdoc-debug` or something, without having to modify the *file).

**Comment by pascalduez** [comment]
`grunt --sassdoc-debug` that's not desirable.

What about `env.debug = options['--debug']` in CLI ?

**Comment by valeriangalliat** [comment]
No problem in CLI, I have already some helper to proxy command line arguments to configuration options.

About plugins, the only use case I see is:

* Run `grunt`;
* It fails;
* Run `grunt --sassdoc-debug` (or `SASSDOC_DEBUG=1 grunt` or whatever you can pass on CLI);
* Paste output in issue.

I don't think it's desirable to have to edit a file to enable debug mode (which is nearly always a temporary option), even for plugins.

**Comment by pascalduez** [comment]
> I don't think it's desirable to have to edit a file to enable debug mode (which is nearly always a temporary option), even for plugins.

You won, good argumentation :-)

With Grunt it's fairly easy to pass arguments, not sure about the others. Especially because there's no more Gulp plugins anymore \o/.

**Comment by valeriangalliat** [comment]
Well for sure `SASSDOC_DEBUG=1 grunt|gulp|any` will work, since we can always access environment variables. :smile:

**Comment by pascalduez** [comment]
:+1:

**Comment by FWeinb** [comment]
:+1:
