### ISSUE TITLE
Bring back `parse` function

### ISSUE THREAD

**Issue by valeriangalliat** [SassDoc/sassdoc#318]
During the last stream refactoring, we dropped the `parse` function, which allowed the user to parse an input and directly get the data.

It's an useful feature, and we can bring it back and adapt it to the new API style. The proposed interface is:

```js
sassdoc.parse(src, env)
  .then(console.log);

vfs.src(src)
  .pipe(sassdoc.parse(env))
  .pipe(through.obj(console.log));
```

And also:

```sh
sassdoc src --parse > data.json
sassdoc src -p > data.json
```

**Comment by pascalduez** [comment]
I guess the returned `data` should be a js object for API usage, and a JSON object on the CLI.

Also wondering whether the returned stream should emit `data` as a whole Buffer or emit it in chunks.

**Comment by valeriangalliat** [comment]
> I guess the returned data should be a js object for API usage, and a JSON object on the CLI.

Yep.

> Also wondering whether the returned stream should emit data as a whole Buffer or emit it in chunks.

We can have `data` only as a whole because of post process. There's no reason to send it chunked.

**Comment by valeriangalliat** [comment]
BTW if we output JSON to stdout, and verbose mode is on, we have to output **all** logs to stderr. And I think it should be the case in every mode… that is, replace `console.log` by `console.warn` for regular logs in our logger.

**Comment by pascalduez** [comment]
> There's no reason to send it chunked.

That's the default (and whole concept) with streams, but agree that in our case this would make it less practical, and also `data` size have few chances to reach problematic levels. (I hope)

**Comment by valeriangalliat** [comment]
> That's the default (and whole concept) with streams

In our case, we would need to chunk manually the data (we already have as a whole) and send it by chunk. It doesn't makes sense, nor helps in any way.

> and also data size have few chances to reach problematic levels. (I hope)

I don't see a reason why it could be problematic, we have the full data object already loaded, and we only pass a reference to the next object handler… I mean it will be problematic if we waste all the available RAM with the data object, but that's not specific to streaming API, it will make SassDoc fail in all cases.
