### ISSUE TITLE
Use `const` instead of `let` for `require` imports

### ISSUE THREAD

**Issue by valeriangalliat** [SassDoc/sassdoc#319]
We slightly discussed this on Slack, it looks like using `const` for `require` imports is common practice in ES6, and it would indeed enforce imported modules cannot be modified, which is a good thing.

The following script can do all the work for us:

```sh
# GNU `sed`
find src -name '*.js' -exec sed -ri 's/let ([^ ]*) = require/const \1 = require/' {} +

# BSD/Mac `sed`
find src -name '*.js' -exec sed -E -i '' 's/let ([^ ]*) = require/const \1 = require/' {} +
```

Opinions? I'm all for `const` personally.

**Comment by HugoGiraudel** [comment]
I trust your advice.

**Comment by FWeinb** [comment]
:+1:

**Comment by valeriangalliat** [comment]
I run the script when #318 is merged.
