### ISSUE TITLE
Does the document can show the path of a special mixin?

### ISSUE THREAD

**Issue by andge** [SassDoc/sassdoc#325]
there are many files in the folder .so when i generate the doc through sassdoc,there are no info aboat where the mixin is from.

so,can you support it ?

thank you

**Comment by valeriangalliat** [comment]
Hi @andge,

There's a feature kinda similar to what you want; if you configure a `basePath` (see [Customizing The View](http://sassdoc.com/customising-the-view/)) so SassDoc can link to your file URL, by adding a "View source" link near your "items", linking to `{{ basePath }}/{{ filePath }}`.

However it might be an interesting idea to display the actual file path in the documentation (not just a "View source" link), and this wouldn't even require a `basePath` to be set (but if one is set, we can make it a link too, and maybe remove the actual "View source"). Opinions on this @SassDoc/owners?

**Comment by pascalduez** [comment]
At the very beginning we had a "found at" thing displayed in the theme, is that still implemented ?

**Comment by valeriangalliat** [comment]
Moved the issue to https://github.com/SassDoc/sassdoc-theme-default/issues/45.
