### ISSUE TITLE
Example with interpolation is not rendered

### ISSUE THREAD

**Issue by willemdewit** [SassDoc/sassdoc#327]
When I try to generate documentation for the following SCSS:

    /// The CSS selector for a special button.
    ///
    /// @example
    /// #{$special-button-selector} {
    ///     font-weight: bold;
    /// }
    $special-button-selector: '.button.special-button';

The example is not rendered. The generated documentation looks like this:
![image](https://cloud.githubusercontent.com/assets/1481860/5813300/93e64570-a07b-11e4-9566-6e3183913add.png)

**Comment by HugoGiraudel** [comment]
That is really odd. Ping @SassDoc/owners.

**Comment by FWeinb** [comment]
You need to indent the example could one level further than the annotation.

**Comment by HugoGiraudel** [comment]
There is absolutely no reason to.

**Comment by valeriangalliat** [comment]
I can't reproduce with 2.0:

```js
[
  {
    "description": "The CSS selector for a special button.\n\n",
    // ...
    "example": [
      {
        "type": "scss",
        "code": "#{$special-button-selector} {\n    font-weight: bold;\n}"
      }
    ],
    // ...
  }
]
```

**Comment by pascalduez** [comment]
Not really new, some special examples need to be indented.

> Lines starting with @ need to be indented to work correctly.
http://sassdoc.com/develop/annotations/#example-6

Seems to be the case with `#` as well

**Comment by willemdewit** [comment]
Even when I indent the example, it is not rendered.

**Comment by valeriangalliat** [comment]
And I can't even reproduce with SassDoc 1.10.12:

![It works!](http://image.noelshack.com/fichiers/2015/04/1421745324-2015-01-20-101801-1253x690-scrot.png)

And the input is your exact SCSS example, without even indenting.

What SassDoc version are you using (`sassdoc --version`)? What is your operating system?

**Comment by pascalduez** [comment]
I can't reproduce either on osx 10.9
Tested SassDoc `1.0` and `2.0`

**Comment by willemdewit** [comment]
I'm using Windows 8 as operating system. The version of sassdoc is: `1.10.11`.
I made a new project with a single file containing the earlier mentioned example.

**Comment by valeriangalliat** [comment]
Ok I can reproduce with Windows line endings in the input file. Thank you @willemdewit for reporting the bug, we will fix it soon.

**Comment by valeriangalliat** [comment]
Ping @FWeinb, looks like it's CDocParser, with Windows line endings, [this](https://github.com/FWeinb/CDocParser/blob/f76d0a56713c87b5ed4ae779478164e4e5f8b40c/index.js#L176) will match only the first line of a comment (and so each line of the comment is considered as its own comment block, and only the last one is affected to an actual item).

**Comment by FWeinb** [comment]
I released an update to `cdocparser@0.12.1` this will be supported in SassDoc 2.0 (But we need to release a update to the SassDoc rc first)

**Comment by valeriangalliat** [comment]
@willemdewit You can run `npm update -g sassdoc` (`-g` if you installed SassDoc globally) to get the latest `cdocparser` which supports Windows line endings.

**Comment by willemdewit** [comment]
Thank you all for your support and quick fixing of the issue! I'm running with sassdoc version `2.0.0-rc.6` now and the examples are generated properly.

**Comment by HugoGiraudel** [comment]
> 2.0.0-rc.6

Please, update to latest (rc.18).

```
npm install sassdoc@beta -g
```

**Comment by valeriangalliat** [comment]
And you will need to upgrade npm to 2.0 for this to work, by running `npm install -g npm@latest`.

**Comment by willemdewit** [comment]
@HugoGiraudel I saw that also, and I was a little early with shouting out that it worked.

The example with the block comments is generated ok, but when I use interpolation I get a sass error. So I switched to the line comments, but then the documentation contains only the last line of the example. Just as what the this issue is saying.

**Comment by valeriangalliat** [comment]
@willemdewit The bug where the documentation contains only the last line of the comment is due to Windows line endings, but it's supposed to be fixed in CDocParser 0.12.1.

Make sure you update your SassDoc installation with `npm install sassdoc@beta -g`. You can check your CDocParser version with `npm ls -g cdocparser`.

**Comment by HugoGiraudel** [comment]
@willemdewit Is it alright now?

**Comment by willemdewit** [comment]
@HugoGiraudel Sorry for the delayed response, after I installed the beta version of grunt-sassdoc also it is working correctly. I also see that the block comment support is removed, so I will go through my code base and change it to line comments.

Thank you all for your help and fixing the issue quickly.

**Comment by valeriangalliat** [comment]
@willemdewit BTW there's a little script to convert block comments to line comments [here](https://github.com/SassDoc/sassdoc/blob/3fe55f0599006fa027889985f24ac36004871067/UPGRADE-2.0.md#c-style-comments). It's not perfect bot for sure can help to port a whole codebase without going full manually.
