### ISSUE TITLE
How to correctly output @example of @include or @extend 

### ISSUE THREAD

**Issue by Skoks** [SassDoc/sassdoc#328]
It looks like parser chokes every time I try to generate something like this and outputs nothing to the styleguide: 

/**
    @example
    @include mixin($arg);
*/

Is there any other way to output @example for `@include` or `@extend`, than spacing or quoting, because it get rendered in the styleguide ? 

/**
    @example
        @include mixin($arg);
*/

/**
    @example
    '@include mixin($arg);'
*/

**Comment by HugoGiraudel** [comment]
Hey. Stick to recommend comments, and indent the `@include` annotation. :) It's written in the docs: http://sassdoc.com/develop/annotations/#example.

```scss
/**
 * @example
 *   @include mixin($arg);
 */
```

Cheers.

**Comment by Skoks** [comment]
@HugoGiraudel Will do, thanks man! :ok_hand:

**Comment by indrekpaas** [comment]
Indenting the example block also indents the code in rendered output, which is not a desired effect. Can the indentation be removed from the output?

**Comment by pascalduez** [comment]
@indrekpaas See SassDoc/sassdoc-theme-default#76
