### ISSUE TITLE
not working with gulp without using gulp-sassdoc

### ISSUE THREAD

**Issue by newtonianb** [SassDoc/sassdoc#329]
I read that gulp-sassdoc is being deprecated and I tried to follow the instructions to use directly but I'm getting the following error:

I did follow the instructions exactly on the website for 2.0. I upgrade to npm 2.0 and installed sassdoc.
BTW it works fine if I use the command line sassdoc but not through gulp.

```
[02:16:37] 'sassdoc' errored after 3.16 ms
[02:16:37] TypeError: undefined is not a function
    at Gulp.<anonymous> (D:\project\tools\gulp\tasks\sassdoc.js:9:15)
    at module.exports (D:\project\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\project\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\project\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\project\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at c:\Users\XX\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

I have a pretty straightforward gulp task
```
'use strict';
var gulp = require('gulp');
var config = require('../config/sassdoc');
var sassdoc = require('sassdoc');

gulp.task('sassdoc', function () {

    return gulp.src('css/**/*.scss')
        .pipe(sassdoc({dest:'output'}));

});

```

edit: i'm not sure it works in command line after all with sassdoc command. I don't get any errors but no file seem to get parsed

**Comment by pascalduez** [comment]
Try: `npm install sassdoc@beta --save-dev` from the root of your project.

BTW `dest` is optional now.

**Comment by newtonianb** [comment]
@pascalduez thanks! so now it actually compiles with no error but eventhough I put in the right path  the output always gives me "Seems like nothing has been documented yet!"

my structure is something like below and my src is `'css/**/*.scss'`
```
css/folder1/file.scss
css/folder2/_file.scss
css/folder3/folder/11/file.scss
...
```

A sample of my sassdoc syntax is 
```
/// Here is the description
/// On several lines if you will
#my-wrapper {
  width: 200px;
  height: 300px;
}
```

**Comment by valeriangalliat** [comment]
@newtonianb Dou you document any Sass "items" (aka functions, mixins, variables or placeholders)? SassDoc won't document CSS selectors.

**Comment by newtonianb** [comment]
@valeriangalliat ahhh that's why, then it seems to work!
but wait that's a bummer! I was looking for a way to visualize my css classes for re-usability. Is there no way even with sassdoc 2 to do this? I'm pretty sure there use to be tools for sass that did this so I think it's reasonably feasible, future plans at least?

**Comment by valeriangalliat** [comment]
I'm afraid SassDoc is not the tool you're searching for. :/

See related comment: https://github.com/SassDoc/sassdoc/issues/309#issuecomment-69026909

**Comment by newtonianb** [comment]
Thanks!

**Comment by HugoGiraudel** [comment]
Ref: http://sassdoc.com/develop/frequently-asked-questions/#does-sassdoc-support-css-classes-and-ids-
