### ISSUE TITLE
Consider adding a "release" task

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#332]
Tiny but shiny in [sass-convert](https://github.com/eslint/eslint/blob/master/Makefile.js#L350)
- check and exit if git tree is not clean
- bump version
- commit version bump
- tag commit version
- npm publish
- push and push tags (create auto release)

Areas of improvements:
- Update changelog
- Update Github release with changelog ?

Food for thoughts:
- https://github.com/MoOx/setup/commit/b342d209642b383a6a1b1d763ba6d81b9e190cfb
- https://github.com/eslint/eslint/blob/master/Makefile.js#L350

**Comment by valeriangalliat** [comment]
I like it.

**Comment by FWeinb** [comment]
:+1:

**Comment by HugoGiraudel** [comment]
:+1: 

Who takes it?

**Comment by pascalduez** [comment]
Added the tiny version in 9837ff1.
Usage:
```
# patch
make release
```
```
# set the version to bump
make release VERS=major
```

The question is whether it's enough or we want to improve it, add more features like changelog gen.

**Comment by valeriangalliat** [comment]
https://github.com/maxogden/maintenance-modules/issues/1
https://github.com/phuu/npm-release

**Comment by HugoGiraudel** [comment]
@valeriangalliat, do you take it?

**Comment by pascalduez** [comment]
Questions are: 
* Are we satisfied with the current one ? 
* Do we even use it ?
* Which feature additions we want ?

**Comment by valeriangalliat** [comment]
> Are we satisfied with the current one ?

I am.

> Do we even use it ?

I do.

> Which feature additions we want ?

Auto bump, commit and tag maybe? I can live without though…

---

Let's just keep this as a reminder if we want to implement it some day.

**Comment by pascalduez** [comment]
> Auto bump, commit and tag maybe? I can live without though…

That's already in the `release` task.

> 
    check and exit if git tree is not clean
    bump version
    commit version bump
    tag commit version
    npm publish
    push and push tags (create auto release)

`make release` bump a patch.
`make release VERS=major` bump a major
`make release VERS=prerelease TAG=next` untested...

**Comment by valeriangalliat** [comment]
Oh okay, I still used `publish`.

**Comment by HugoGiraudel** [comment]
Can we close?

**Comment by pascalduez** [comment]
Feels like we are not that much excited about an all automatized thing, so I close for now.

**Comment by pascalduez** [comment]
https://www.npmjs.com/package/changelog-maker
