### ISSUE TITLE
Laravel & SassDoc: Gulp task generates nothing, but global CLI command does

### ISSUE THREAD

**Issue by AndersSchmidtHansen** [SassDoc/sassdoc#334]
Heya!

I'm currently trying to integrate SassDoc (awesome job guys, btw) with Laravel, but I've hit a roadblock. I get the "Seems like nothing has been documented yet!" when runnning a Gulp task like `gulp sassdoc`, but NOT when running a native, globally-installed sassdoc command like `sassdoc path/to/sass path/to/docs`. Very weird, myes?

In the new Laravel file structure things like Sass is usually put into a `resources/assets/sass` folder and something like a SassDoc output should go into a `public/docs/` folder.

So running `sassdoc resources/assets/sass public/docs` works brilliantly, but the gulp equivalent doesn't. 

I've tried modifying the options a bunch of times, but no cigar. I've also tried adding the `.sassdocrc` file different places, and also naming it `config.yml` and `config.json`, also nothing.

SassDoc has been installed as `"sassdoc": "beta"` and later as `sassdoc@beta --save-dev`.

Hope you can help, I know you must be busy, so I don't expect anything. Just would be awesome to have SassDoc support integrated with Laravel in an easy way.

Cheers!

**Comment by HugoGiraudel** [comment]
Hey! What does `sassdoc --version` say?

**Comment by AndersSchmidtHansen** [comment]
Ah, of course, it says `1.10.12`! That must be the reason why. I'll upgrade and try again. Sometimes the solution may be right under your nose :)

**Comment by pascalduez** [comment]
If you have installed `sassdoc` with `npm i sassdoc@beta --save-dev` then you should have the latest RC locally on your project. How's you gulp task like ?

Also take some time to read the several examples on running SassDoc with Gulp. Till end of the page ;-)
http://sassdoc.com/develop/gulp/

**Comment by valeriangalliat** [comment]
@AndersSchmidtHansen I think you have SassDoc 1.0 installed globally (the one you run with `sassdoc` CLI command), but you already have the beta (upcoming 2.0) in your `node_modules` directory (because you installed `sassdoc@beta` which is okay).

You need to run `node_modules/.bin/sassdoc` to get the corresponding SassDoc CLI to the version you installed *locally* with npm.

BTW since 2.0 the destination is no more a CLI argument, but an option, and your `sassdoc resources/assets/sass public/docs` must become `sassdoc resources/assets/sass --dest public/docs`.

**Comment by pascalduez** [comment]
So setting a custom destination from Gulp:

```js
var gulp = require('gulp');
var sassdoc = require('sassdoc');

gulp.task('sassdoc', function () {
  return gulp.src('resources/assets/sass/**/*.scss')
    .pipe(sassdoc({
      dest: 'public/docs'
    }));
});
```

**Comment by AndersSchmidtHansen** [comment]
Thanks @pascalduez ;).

Aight, now I have version `2.0.0-rc.21` everywhere. Running `node_modules/.bin/sassdoc --version` also yields `2.0.0-rc.21`. Now, running the CLI command also yields the `Seems like nothing has been documented yet!` result. Don't spend more time on this, you have better things to do, I'll spend some more time to see what's going wrong, since it must be me that's doing something wrong. Thanks anyway!

In any case, my Gulp task is:
```
gulp.task('sassdoc', function () {
  var options = {
    'dest': 'public/docs/sass'
  }
  return gulp.src('resources/assets/sass/**/*.scss').pipe(sassdoc(options));
});
```

**Comment by pascalduez** [comment]
Question, do you have **Sass items** commented ?

**Comment by AndersSchmidtHansen** [comment]
Yeah, I took the thing for a test-run with:

```
 /**
 * This is a poster comment.
 * It will apply annotations to all items from file.
 * @group API
 * @author Hugo Giraudel
 **/

/**
 * This item will have:
 * `@group API` and `@author Hugo Giraudel`
 * inherited from the poster.
 */
@function dummy-function() {
  // ...
}
```

This produced a result with the older, globally installed Sassdoc (which after your replies, I upgraded everywhere, and now produces no result).

**Comment by AndersSchmidtHansen** [comment]
Problem solved (I think), it's because I used the multiline commenting with asterisks and not the `///`. I thought I had understood it as you could do both styles, but after converting the poster comment to the `///` style, things got generated nicely via Gulp.

**Comment by pascalduez** [comment]
We have removed support of CDoc styles comments just a few beta release ago. See #326
