### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#338]
Follow up of #335 
<blockquote> 80% is pretty neat, but I'd like us to bump 90-95% if it's doable.</blockquote>
<blockquote>We won't reach 100% anyway, due to the ES(6|2015) transpilation, there's some snippets from 6to5 that aren't called, and would make no sense for us to test them.
But for sure, we can improve things.</blockquote>

There's some clear areas we can improve:

- [ ] Environment (testing the different scenarios) (75% done) 
- [ ] CLI testing ? Somehow a bit tested in Makefile.
- [x] Making sure all annotations are fully tested
- [x] Add a test for `exclude` 
- [x] Maybe make a try to move `--parse` tests form Makefile to unit tests ?

Track

[![Coverage Status](https://coveralls.io/repos/SassDoc/sassdoc/badge.svg?branch=develop)](https://coveralls.io/r/SassDoc/sassdoc?branch=develop)

Stand 2015-01-27

![screen shot 2015-01-27 at 10 39 19](https://cloud.githubusercontent.com/assets/335467/5916417/452843d4-a611-11e4-8838-1993e5dff58f.png)

**Comment by HugoGiraudel** [comment]
Do you feel like you can close this issue in 3 days?

**Comment by pascalduez** [comment]
Yep.

**Comment by HugoGiraudel** [comment]
Moving this to 2.1.

**Comment by pascalduez** [comment]
We will ship 2.0 with min 91% as you can see, so I guess we're good :-)

**Comment by pascalduez** [comment]
Stand 2015-01-30

![screen shot 2015-01-30 at 16 04 41](https://cloud.githubusercontent.com/assets/335467/5977628/d0405fda-a899-11e4-84e1-44ec471ddaa2.png)

**Comment by valeriangalliat** [comment]
Wow, awesome!

**Comment by HugoGiraudel** [comment]
It looks like `errors.js` could be a bit more tested?

**Comment by pascalduez** [comment]
Comment above is already outdated :-)
Remaining bits are in Environment.js and sassdoc.js basically. Also a bit dependent on #345

**Comment by pascalduez** [comment]
2015-02-03

![screen shot 2015-02-03 at 23 21 00](https://cloud.githubusercontent.com/assets/335467/6030937/632fda1e-abfb-11e4-9005-6958c91550b5.png)

**Comment by HugoGiraudel** [comment]
What is your feeling on this @pascalduez?

**Comment by pascalduez** [comment]
I will keep on adding tests over time. There's still room for improvements, even if at some point the tests might becomes a bit clumsy. 
No milestone needed IMO.

**Comment by HugoGiraudel** [comment]
What's the status here?

**Comment by HugoGiraudel** [comment]
Where do we stand here? Can we close now that it is quite obvious that we should have best code coverage at all time?

**Comment by HugoGiraudel** [comment]
Can we close this?

**Comment by pascalduez** [comment]
If we consider we are happy with the current coverage.
I have some in progress work on this, somewhere... The uncovered things are not that easy to test.
