### ISSUE TITLE
Environment issues/questions

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#345]
**[draft][wip]**

While working on unit tests for Environment, a number of questions raised.

###### 1 
When Environment fail to find a custom theme, and thus falling back to default theme, shouldn't `env.themeName` be changed to `'default'` then ?
Right now it stays with the failing theme name.
*It's no big deal since that key does not seem used afterward, but just for consistency/logic*

###### 2
When there is no `package` key in a config, or **no config at all**, shouldn't Environment try to load the `package.json` from current project/cwd ?
Right now: `{}`
If a passed in `package` key is failing, the fallback happens successfully though.

###### 3
`Environment.load` accepts three types of config: String, Object or undefined.
The object check is `typeof config === 'object'`. 
Thus `Environment.load([`:trollface:`]);` boom.

###### 4
`strict` can't be set from config. 
It is part of the Environment Object when [loadObject](https://github.com/SassDoc/sassdoc/blob/develop/src/environment.js#L78-L83) checks are done.

**Comment by valeriangalliat** [comment]
> When Environment fail to find a custom theme, and thus falling back to default theme, shouldn't `env.themeName` be changed to `'default'` then ?

Yes.

> When there is no `package` key in a config, or **no config at all**, shouldn't Environment try to load the `package.json` from current project/cwd ?

It's a "bug" it's not fallbacking like when a `package` key is failing. It should search a `package.json` in both cases.

> `Environment.load` accepts three types of config: String, Object or undefined.
> The object check is `typeof config === 'object'`.
> Thus `Environment.load([:trollface:]);` boom.

An array is never expected as a parameter to `Environment.load`.

**Comment by pascalduez** [comment]
> An array is never expected as a parameter to Environment.load.

Sure, but it wouldn't hurt to reinforce the check, and then it will throws a meaningful Error.

Actually those points are not necessarily release blockers, except maybe 2. 
But they could be patched later.

**Comment by valeriangalliat** [comment]
> Sure, but it wouldn't hurt to reinforce the check, and then it will throws a meaningful Error.

Makes sense.

**Comment by HugoGiraudel** [comment]
Can we close?

**Comment by pascalduez** [comment]
None of those has been addressed.
Question is can wait till 2.1 ?

**Comment by HugoGiraudel** [comment]
You tell me.

**Comment by valeriangalliat** [comment]
Everything can be delayed, yes.

**Comment by HugoGiraudel** [comment]
Who takes this? @valeriangalliat?

**Comment by valeriangalliat** [comment]
Yes.

**Comment by valeriangalliat** [comment]
> `strict` can't be set from config.
> It is part of the Environment Object when loadObject checks are done. 

This is because we otherwise don't know how  to do error handling (strict or not) in the early boot parts, like if the config file is not found.
