### ISSUE TITLE
npm install warning.  denodeify

### ISSUE THREAD

**Issue by dkebler** [SassDoc/sassdoc#366]
deprecated promise-denodeify@1.2.2: THIS PROJECT IS NO LONGER MAINTAINED by clebert.

Need to be concerned about this?
I just upgraded to node v0.12 and the latest npm this morning before installing sassdoc.

**Comment by valeriangalliat** [comment]
No need to worry with this warning, the library is no longer maintened by its author but it's working pretty fine!

I'm thinking to make my own replacement of this library to avoid the warning, but there's no problem with the current one. :)
