### ISSUE TITLE
Sassdoc won't compile

### ISSUE THREAD

**Issue by bgriffith** [SassDoc/sassdoc#368]
Sassdoc won't compile after I did a fresh install. Any ideas? It's the same deal for a friend too.

Running node v0.12.0
```
/Users/ben/.node/lib/node_modules/sassdoc/dist/errors.js:13
  _to5Helpers.inherits(SassDocError, Error);
              ^
TypeError: undefined is not a function
    at /Users/ben/.node/lib/node_modules/sassdoc/dist/errors.js:13:15
    at Object.<anonymous> (/Users/ben/.node/lib/node_modules/sassdoc/dist/errors.js:25:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ben/.node/lib/node_modules/sassdoc/dist/environment.js:8:49)
    at Module._compile (module.js:460:26)
```

**Comment by valeriangalliat** [comment]
Looks like a strange bug with 6to5/6to5-runtime… I published an hotfix (sassdoc@2.0.8) ensuring precise version of 6to5-runtime to make it work.

Thanks for reporting.

**Comment by cibulka** [comment]
Same problem just appeared for me:

```
Registering "/Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/tasks" tasks.
Loading "sassdoc.js" tasks...ERROR
>> TypeError: undefined is not a function
>>     at /Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/errors.js:15:17
>>     at Object.<anonymous> (/Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/errors.js:25:3)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/environment.js:9:51)
>>     at Module._compile (module.js:460:26)
```

I spent an afternoon before looking for solution for another node/Grunt problem, that magically fixed itself - so just in case it is related, here is the discussion about it: https://github.com/npm/npm/issues/7349

According to `npm list sassdoc`, I am using sassdoc 2.1.2.:

```
cibulka-wp-theme@1.0.0 /Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme
└─┬ grunt-sassdoc@2.0.0
  └── sassdoc@2.1.2 
```

Here is my Gruntfile (in case the problem would stem from configuration): https://gist.github.com/cibulka/87f3259ff27f8db105e1 It worked just a few hourse ago ...

**Comment by valeriangalliat** [comment]
Hi @cibulka,

I can't reproduce the bug with a similar Gruntfile but containing *only* the SassDoc task… it looks like it's a Babel runtime error, the 15th line of `dist/errors.js` is `_babelHelpers.createClass(SassDocError, {`.

But maybe Babel already fixed it and a `npm update` could fix it?

Otherwise, is your whole project accessible somewhere so I can try to reproduce the bug?

**Comment by cibulka** [comment]
Thanks for quick response!

The project is not accessible anywhere at the moment (although I can make it happen, if it would help). 

I've done a bunch of `npm update` calls because of the problem I was trying to solve before. My Babel version (according to `npm list`) is 4.7.1 which seems to be current.

How likely is it that the error is caused by my Gruntfile configuration? I can remove all the project specifics from it and see if the error persists.

**Comment by cibulka** [comment]
Also, `npm uninstall grunt-sassdoc` throws following error:

```
| => npm uninstall grunt-sassdoc
unbuild grunt-sassdoc@2.0.0
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/Cibulka/.node/bin/npm" "uninstall" "grunt-sassdoc"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0
npm ERR! path /Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules
npm ERR! code ENOTEMPTY
npm ERR! errno -66

npm ERR! ENOTEMPTY, rmdir '/Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/npm-debug.log
```

Does that help? Thanks again!

**Comment by pascalduez** [comment]
Good chances are this is yet another conflict with on a the grunt-plugins either directly or one of their many dependencies, similar to #360, #354.

Although we tried to reduce our usage of natives polyfills.

**Comment by valeriangalliat** [comment]
Okay, we have the same Babel version and it's the latest.

My Gruntfile is the following:

```js
module.exports = function (grunt) {
  grunt.initConfig({
    sassdoc: {
      parent: {
        src: 'sassdoc-theme-default/scss',

        options: {
          dest: 'parent',
          verbose: false,
          package: {},
          theme: 'default',
        },
      },
      child: {
        src: 'sassdoc-theme-default/scss',

        options: {
          dest: 'child',
          verbose: false,
          package: {},
          theme: 'default',
        },
      },
    },
  });

  grunt.loadNpmTasks('grunt-sassdoc');
  grunt.registerTask('default', ['sassdoc']);
};
```

Does it work for you? (You can replace `src` by your actual parent/child stylesheets directories).

If so, you should try to add one by one all the other tasks of your initial Gruntfile to this one until the bug appears again so you can identify the conflicting module. Like said @pascalduez, it's possibly a problem with a module messing with global state.

**Comment by cibulka** [comment]
Thank you! I've tried your Gruntfile (with the only change in `src` and `options:dest`), but the problem persists ...

```
| => grunt --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-sassdoc" local Npm module tasks.
Reading /Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/package.json...OK
Parsing /Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/package.json...OK
Loading "sassdoc.js" tasks...ERROR
>> TypeError: undefined is not a function
>>     at /Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/errors.js:15:17
>>     at Object.<anonymous> (/Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/errors.js:25:3)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/cibulka-wp-theme/node_modules/grunt-sassdoc/node_modules/sassdoc/dist/environment.js:9:51)
>>     at Module._compile (module.js:460:26)
Loading "Gruntfile.js" tasks...OK
+ default

No tasks specified, running default tasks.
Running tasks: default

Running "default" task
Warning: Task "sassdoc" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by valeriangalliat** [comment]
Now this is interesting… I would have prefered the second option though (conflicting module). :s

I can reproduce BTW, my mistake was to have an older SassDoc version already installed in my test folder, so installing `grunt-sassdoc` didn't install the latest version alongside. I'll see what I can do.

**Comment by cibulka** [comment]
Okay, I've also tried to install Sassdoc globally with `npm install -g sassdoc`. This is what I get if I call `sassdoc --version` after supposedly successful installation:

```
/Users/Cibulka/.node/lib/node_modules/sassdoc/dist/errors.js:15
  _babelHelpers.prototypeProperties(SassDocError, null, {
                ^
TypeError: undefined is not a function
    at /Users/Cibulka/.node/lib/node_modules/sassdoc/dist/errors.js:15:17
    at Object.<anonymous> (/Users/Cibulka/.node/lib/node_modules/sassdoc/dist/errors.js:25:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Cibulka/.node/lib/node_modules/sassdoc/dist/environment.js:9:51)
    at Module._compile (module.js:460:26)
```

I would prefer the problem with conflicting modules too! :) Thanks for looking into this. Should I open the issue on Babel? Does something similar come up on their issue board? I looked there myself, but since I know pretty much nothing about the library (and what exactly it does), all sounds pretty greek to me.

**Comment by valeriangalliat** [comment]
Aaaand in the `dist/errors.js` from SassDoc npm module, the 15th line is `_babelHelpers.prototypeProperties`, while in my freshly compiled version (against latest Babel) it is `_babelHelpers.createClass`.

So it's a problem we already saw, we can't rely on `^x.x.x` for `babel` and `babel-runtime` requirements, they break stuff (like change `prototypeProperties` to `createClass`) in minor versions.

I'm tightening Babel requirements in SassDoc to patch only (like we did the first time in this very issue, but this time definitely) and I'll release a new version.

**Comment by valeriangalliat** [comment]
Should be fixed with SassDoc 2.1.3!

**Comment by cibulka** [comment]
Perfect! Do you have an idea when will you be able to publish it?

**Comment by valeriangalliat** [comment]
It is published already. :smile:

**Comment by cibulka** [comment]
![](http://s3.postimg.org/wfbadp0vn/giphy.gif)

**Comment by kevin-smets** [comment]
The global install of sassdoc works perfectly for me. However the grunt-sassdoc does not.

    sassdoc --version
    2.1.3

Works lika a charm and I can generate docs with it. 

But I get the same error as stated above when running the bin from grunt-sassdoc, when it gets fixed I can run it properly through the build system again. Thanks for the blazing fast publishing!

**Comment by valeriangalliat** [comment]
@kevin-smets So is it fixed for you too? When you run the Grunt task, it uses the SassDoc version from `node_modules` which is not the same as the globally installed one; you need to update this one too!

**Comment by kevin-smets** [comment]
Eh, ok, seems I installed grunt-sassdoc JUST before you pushed the update or something :). My grunt list still showed v2.1.2. Ran ```npm install grunt-sassdoc``` again and now everything is working perfectly.

Awesome work. Time to release the docs!

(just a minor remark, the logo still shows the old style of commenting /**, time to update?)

**Comment by valeriangalliat** [comment]
Cool!

About the logo: http://sassdoc.com/frequently-asked-questions/#why-does-the-logo-show-a-type-of-comment-that-is-not-supported

**Comment by kevin-smets** [comment]
:+1:
