### ISSUE TITLE
WTF with 6to5-runtime?

### ISSUE THREAD

**Issue by valeriangalliat** [SassDoc/sassdoc#369]
* #368
* 8bab18915b9fa7df6c764bb3211ecfb7acc491b1

We need to find a decent way to depend on 6to5-runtime without it breaking SassDoc when newer 6to5-runtime versions are published… not sure a hardcoded strict version like done in 8bab18915b9fa7df6c764bb3211ecfb7acc491b1 is the right solution.

**Comment by pascalduez** [comment]
I'm starting more and more to limit my usage of ES6 features to a restricted set, so I can ship code not runtime dependent or exposed to versions break, global scope or native hijacking, and all that jazz.
See [3bbea0c](https://github.com/SassDoc/sass-convert/commit/3bbea0ca4ca2a6f38adf120cfe032afed0c0366f)
In sassdoc' case that would mean renouncing to async functions I guess, which sucks. So I don't know.
A fixed dependency is not that bad.

**Comment by valeriangalliat** [comment]
> I'm starting more and more to limit my usage of ES6 features to a restricted set, so I can ship code not runtime dependent or exposed to versions break, global scope or native hijacking, and all that jazz.

I agree with this philosophy.

Not sure we have to renounce to async functions, we can, well, still use regenerator, and some library providing `Promise.do` or equivalent. But using a raw promise flow instead of async functions is acceptable to me.

About this very issue, I think there's probably a bug with 6to5, or a non-BC change, or **we're not using 6to5 properly**? I'm still not sure how we should use 6to5 as a library developers, I can't find documentation extensive about this. Looks like `selfContained` with runtime is nice, but now, what about version requirements, compatibility with 6to5 and 6to5-runtime dependency? They just say [`npm install --save 6to5-runtime`](https://6to5.org/docs/usage/transformers/#self-contained) as we did.

BTW @pascalduez if we start using Bluebird, we can tell 6to5 to [compile async functions as coroutines](https://6to5.org/docs/usage/transformers/#bluebird-coroutines)!

**Comment by pascalduez** [comment]
I don't feel we are doing something wrong, It looks like they are intensely active to patch and release, breaking things along the road... But fixing them as quick though.
We could either fix the dependency, or allow only patches.

Last time I checked Bluebird coroutines required the --harmony flag. And looks like even Node 0.12 doesn't support generators. Seducing idea though.

**Comment by HugoGiraudel** [comment]
So what is the idea here? :x

**Comment by valeriangalliat** [comment]
Currently, we stick with hardcoded 6to5 version. We may allow patch…

Bumping minor should require manual check, due to previous experiences.
