### ISSUE TITLE
Gitter channel for SassDoc

### ISSUE THREAD

**Issue by varemenos** [SassDoc/sassdoc#370]
It would be great if this project had a Gitter channel for asking some quick questions instead of creating an issue and bloating the issue tracker.

**Comment by pascalduez** [comment]
Why not, in the meantime http://sassdoc.com/contributing/#asking-a-question

**Comment by varemenos** [comment]
I did read the FAQ and the question I wanted to ask wasn't there and the Slack channel you have is not accessible without an invite

**Comment by HugoGiraudel** [comment]
Any way for Slack to have an open channel?

**Comment by varemenos** [comment]
I dont think it's possible

**Comment by HugoGiraudel** [comment]
There it is: https://gitter.im/SassDoc/sassdoc.
