### ISSUE TITLE
Logo uses old unsupported syntax

### ISSUE THREAD

**Issue by SteveEdson** [SassDoc/sassdoc#371]
The logo uses the `/**` syntax, however, SassDoc clearly states

> * Are you still using `/**` comments ? They're no more supported since 2.0.
    See <http://sassdoc.com/upgrading/#c-style-comments>.

**Comment by valeriangalliat** [comment]
Hehe you're not the first one to be surprised by the logo! See [Why does the logo show a type of comment that is not supported?](http://sassdoc.com/frequently-asked-questions/#why-does-the-logo-show-a-type-of-comment-that-is-not-supported) from the FAQ.

**Comment by SteveEdson** [comment]
Sorry, I searched the issues and found no mention of it. I'll do a more thorough search next time!
