### ISSUE TITLE
"Deprecated"-label not properly styled

### ISSUE THREAD

**Issue by CREEATION** [SassDoc/sassdoc#377]
Hello,

the deprecated label in the docs seems to be broken, as you can see here:

![bildschirmfoto 2015-02-26 um 17 27 24](https://cloud.githubusercontent.com/assets/3277769/6396104/ea875756-bddc-11e4-806c-baa8db8c5d9d.png)

I tried it both with and without a description... or am I missing something?
I'm on a Mac with Chrome.

Thomas

**Comment by pascalduez** [comment]
Moved to SassDoc/sassdoc-theme-default#73

Thanks for reporting !
