### ISSUE TITLE
Add ability ot handle i18n

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#381]
After seeing this [tweet](https://twitter.com/ffoodd_fr/status/573398039987130368) I'm wondering how much efforts it would be to bring translation capabilities.
Let's just brainstorm for now.

Maybe something that could leverage [Transifex](https://www.transifex.com/)

**Comment by valeriangalliat** [comment]
Should be moved to the theme, apart from the CLI and exception messages we don't have any text in the core, and I don't think we need to make these translatable.

In the theme, nearly all data comes from the stylesheet comments, that would mean we need a way to translate stylesheet comments too? Or just the theme UI, like "Description", "Type", "Close all", "Search"?

**Comment by HugoGiraudel** [comment]
I was thinking about that just a couple of days ago. I'll give my thoughts
when I come back to France next week.

Le Jeu 5 Mar 2015 10:36, Valérian Galliat <notifications@github.com> a
écrit :

**Comment by pascalduez** [comment]
> Should be moved to the theme, apart from the CLI and exception messages we don't have any text in the core, and I don't think we need to make these translatable.

You're right, most likely this would be a theming job. 

<br>
For instance, let's look at a simple example [FxOS Boilerplate](https://github.com/robnyman/Firefox-OS-Boilerplate-App):

Translatable [HTML elements](https://github.com/robnyman/Firefox-OS-Boilerplate-App/blob/gh-pages/index.html#L38) are given a `data-l10n-id` data attribute.

```html
<h1 data-l10n-id="app-heading">Firefox OS Boilerplate App</h1>
``` 
Which serves as a reference for the [translation files](https://github.com/robnyman/Firefox-OS-Boilerplate-App/blob/gh-pages/locales/fr/app.properties#L1)
```
app-heading  = Modèle d’application pour Firefox OS
``` 

It's using the [l10n.js lib](https://github.com/mozilla-b2g/gaia/blob/master/shared/js/l10n.js) which is derived from [webL10n](https://github.com/fabi1cazenave/webL10n). So it's actually "in browser" translation.

Works great for "fixed" interface elements, but not sure how to deal with generated content. Automatic ID generation ? `data-l10n-id="mixin-name-param-name"` They might quickly become a mess.

Since SassDoc theme are compiled, we could also think of something at compilation time, that would generate several indexes. We need a lib to care about plurals and stuff.

**Comment by HugoGiraudel** [comment]
I’m not in favour. Code documentation should be in English, 99% of the case, and I don’t feel like it’s a good idea to design for edge cases. On top of that, it is probably possible to create a SassDoc theme including a translation system. I doubt this should be part of the core.

**Comment by valeriangalliat** [comment]
^ this

**Comment by pascalduez** [comment]
SassDoc core shouldn't be adding more syntax and stuff to achieve this.
It would rather be a custom theme job.

It might already be possible to use a string extraction tools, like in Python. So one would need to wrap the translatable strings in something like `_("A string")` and then work with .po files or similar.
