### ISSUE TITLE
@access annotation should override privatePrefix

### ISSUE THREAD

**Issue by davidkpiano** [SassDoc/sassdoc#384]
Please feel free to mark as invalid if this is working as designed.

If I have a function/mixin prefixed with a "conventionally private" underscore (though it may or may not be private) and an `@access` annotation is provided, the explicit value of `@access` should take precedence over the privatePrefix (without needing to mess with a configuration file). See example:

```scss
/// Creates a list of elements split into groups the length of `$size`.
/// If `$collection` can't be split evenly, the final chunk will be the remaining
/// elements.
///
/// @access public
/// @group List
/// @param {List} $list The list to process.
/// @param {number} $size [1] - The length of each chunk.
/// @returns {List} Returns the new list containing chunks.

@function _chunk($args...) {
    // ...
}
```

The generated Sassdoc will manifest this as **[private]**, despite the `@access public` annotation.

**Comment by pascalduez** [comment]
Agree, `@access` annotation should take precedence over autofilled value.
Marking this as a bug.

**Comment by valeriangalliat** [comment]
I'm not sure it's a design decision, I think it's more a consequence of how work default annotations values. All items are `@access public` by default, meaning SassDoc don't have a way to distinguish between explicit `@access public` and the default value.

I'm trying a patch with `auto` default value…

**Comment by valeriangalliat** [comment]
Fixed since 2.1.4!

**Comment by pascalduez** [comment]
:+1:

**Comment by davidkpiano** [comment]
Much thanks @valeriangalliat! :smile:
