### ISSUE TITLE
Have `@name` optionally overwrite only the document name, not item name

### ISSUE THREAD

**Issue by indrekpaas** [SassDoc/sassdoc#390]
If I would have `@mixin qty($expr) { ... }` it would name the document **qty** by default. I would like to override this with `@name quantity` for the document and preserve the `qty` for the mixin, but the mixin name gets overwritten as well.

**Comment by pascalduez** [comment]
Currently SassDoc is not really "file centric".
Except for [File-level annotations](http://sassdoc.com/file-level-annotations/) which are file scoped, there isn't any file organizational feature. 
The correct way to organize items is by using the `@group` annotation.

The `@name` annotation only deals with items names, not files.

Files are used to link to the proper item source, so overriding a file name would break those paths.

Or maybe I'm missing something in what your trying to achieve ?

**Comment by HugoGiraudel** [comment]
Ping @indrekpaas. Could you reply to @pascalduez so we can now where you stand? :)

**Comment by indrekpaas** [comment]
@pascalduez @HugoGiraudel Is there a possibility to separate document name and item name? Have the current behaviour as the default, but offer a way to override either? 

Coming back to my example, having an abbreviated document name **(qty)** in the (left-hand) document tree isn't really descriptive. Being able to rename this to something more meaningful **(quantity query)** without modifying the actual item (mixin) name is desired.

Otherwise to keep the meaningfulness in the documentation means having to keep the item (mixin) names long in the code.

**Comment by HugoGiraudel** [comment]
You could (should?) use aliases.

**Comment by pascalduez** [comment]
> Is there a possibility to separate document name and item name?

File names and item names are not linked in any way, so you can set them separately.

What appears in the default theme left hand column are the groups, not the file names.

If I understand your issue, you could use the following strategy:

```scss
/// A quantity-query builder
/// @group quantity-queries
/// @param ....
@mixin qty(...) { ... }
``` 
.sassdocrc
```yaml
groups:
  quantity-queries: Quantity queries
```

**Comment by indrekpaas** [comment]
@pascalduez What I meant by separating the document and item name is this: a document gets its name from the item name. If the mixin was called `qty`, the document is called `qty` from that reference. Now the left hand column shows this document `qty` under "General" or some other, specified, group.

When I would want to rename the document's default name `qty` to `quantity`, the item name is renamed as well, showing `@mixin quantity(...) { ... }` in the parsed code block while the original `@mixin qty(...) { ... }` remains in the code.

Thank you for the code example above, it solved another issue I had hard time wrapping my head around.

**Comment by pascalduez** [comment]
Obviously I missing something here :-)

Let's try to be as clear as possible:

- [SassDoc defaut theme] does **not** display the file names in any manner.
- [SassDoc defaut theme] displays **groups** in its left hand column, not file names.
- The only usage of files that is made, is to [link to the item source](https://github.com/SassDoc/sassdoc-theme-default/blob/fa836b47c51479ccab60499bfa441beb59b42cf5/views/includes/annotations/preview.html.swig#L11). If `basePath` is provided.

So really you can name your files the way you want, whatever items are inside. And independently of groups or items.

I'm pretty sure that with `@group` `@name` `@alias` there are all the tools needed to play with your items.
[SassDoc defaut theme]: https://github.com/SassDoc/sassdoc-theme-default

**Comment by indrekpaas** [comment]
@pascalduez @HugoGiraudel Thank you, `@alias` is the way to go.
