### ISSUE TITLE
Allow SassDoc comment block to begin with `@ignore` annotation

### ISSUE THREAD

**Issue by indrekpaas** [SassDoc/sassdoc#395]
The title might be somewhat misleading, but it's essentially the issue. I'm trying to utilise `@ignore` annotation to visually distinct SassDoc comment blocks in my source files from the rest of the content:

```scss
/// @ignore ----------------------------------------------------------------
///
/// Description
/// @group Random
///
/// @ignore ----------------------------------------------------------------
```

Unfortunately the description gets ignored as well and parsing resumes from the next annotation. Is this expected behavior or can this be improved?

Thank you in advance! 
I'm over the moon with SassDoc if I haven't said this already.

**Comment by indrekpaas** [comment]
I could just use Sass' single line comments to achieve similar result,

```scss
// -------------------------------------------------------------------------
//
/// Description
/// @group Random
//
// -------------------------------------------------------------------------
```

but I guess it would come at the cost of consistency and aesthetics.

**Comment by HugoGiraudel** [comment]
We made it possible for authors to use dashes in comments explicitly to
give the ability to draw horizontal lines between annotations or whatever.
I recommend you do that. `@ignore` is not meant to do that.

**Comment by indrekpaas** [comment]
Thank you!
