### ISSUE TITLE
Line breaks in @example annotation not preserved

### ISSUE THREAD

**Issue by alademann** [SassDoc/sassdoc#405]
Hi there,

Using the latest version of sassdoc, line breaks within the `@example` annotations don't seem to be preserved... Is this a bug? Or am I doing something wrong in my template?

__Src Annotation:__

```scss
/// @example scss - Sass Implementation
///   .visible-retina-and-up {
///       display: none;
///   }
///   // Param value will always be
///   //   `#{$key}+ resolution` for inclusive-ascending
///   // Or
///   //   `#{$key}- resolution` for inclusive-descending
///   // Where $key is a map key within the
///   //   `$ddpx-resolutions` map
///   @include respond-to('retina+ resolution') {
///       // resolutions 2dppx and higher
///       .visible-retina-and-up {
///           display: block;
///       }
///   }
/// ---
/// @example css - CSS Output
///   .visible-retina-and-up {
///       display: none;
///   }
///
///   @media only screen and (min-resolution: 2dppx),
///          only screen and (-webkit-min-device-pixel-ratio: 2),
///          only screen and (min--moz-device-pixel-ratio: 2),
///          only screen and (min-resolution: 192dpi) {
///       .visible-retina-and-up {
///           display: block;
///       }
///   }
```

---

__Template:__
```html
{{ example.code | escape | safe }}
```

---

__Output:__

![sassdoc-no-linebreaks](https://cloud.githubusercontent.com/assets/348643/7815051/ed634e1a-037a-11e5-9cd6-d4ee79d7a43b.png)

**Comment by HugoGiraudel** [comment]
That's odd. Are you using th edefault theme?

**Comment by valeriangalliat** [comment]
There's no problem with the default theme on my side.

@alademann, are the line break present in the `<code>` tag in the HTML source? Is the code in some kind of `<pre>`? Otherwise line breaks are treated as spaces like anywhere else in HTML.

**Comment by alademann** [comment]
@valeriangalliat @HugoGiraudel I am not using the default theme... however - my template wraps the `<code>` block just like the default theme does... in a `<pre>`

__sassdoc-theme-default__
```html
<pre class="example__code  language-{{ example.type }}"><code>{{ example.code|escape|safe }}</code></pre>
```

The line breaks do not appear to be present in the generated html.

**Comment by alademann** [comment]
@HugoGiraudel @valeriangalliat I think the problem is in the translation of the code when I pass the result to pygments.rb (what i'm using for code coloring)... so the issue isn't on your end. Sorry about that.
