### ISSUE TITLE
Add Sitemap Generation Feature

### ISSUE THREAD

**Issue by Skoks** [SassDoc/sassdoc#411]
Great project guys, 

Super useful and handy :+1::metal:.

I would like to request a sitemap generation feature, I believe that every website will benefit from having one. 

From [Google Learn About Sitemaps](https://support.google.com/webmasters/answer/156184)

>__Your site is new and has few external links to it__. Googlebot and other web crawlers crawl the web by following links from one page to another. As a result, Google might not discover your pages if no other sites link to them.

**Comment by pascalduez** [comment]
Greetings,

most available themes are composed of one and only `index.html`.
Does a sitemap makes sense in such case ?

Not sure it should be SassDoc responsibility to deal with those kind of features, there should already be CLI tools available ?

It would be implemented at a theme level anyway, using something like [sitemap-static](https://github.com/tmcw/sitemap-static) (no API atm).
Or another `sassdoc-extra` filter.

**Comment by valeriangalliat** [comment]
Yep, the default theme being single-page, I don't think it makes sense to add a sitemap. Any external link to a SassDoc documentation is a link to "the whole site" and there's nothing more to discover.

**Comment by HugoGiraudel** [comment]
Agreed. There is no point for SassDoc to implement such a feature. If you
truly want it, I suggest you build your own theme or fork the default one.

Le dim 7 juin 2015 21:34, Valérian Galliat <notifications@github.com> a
écrit :

**Comment by Skoks** [comment]
Thank you for your quick responses.

I agree with you now! 
Missed the fact that it's a single page website, shame on me :speak_no_evil:

**Comment by HugoGiraudel** [comment]
We do appreciate that you come up with new features though. We have been slowing down with SassDoc lately but new interesting features might get us back on track. :)
