### ISSUE TITLE
Strange @since styling

### ISSUE THREAD

**Issue by TheDutchCoder** [SassDoc/sassdoc#416]
The current styling on the @since annotation is quite strange.
It's put on the right side, above the actual element, which sometimes makes it look like it belongs to something else.

Example:
![image](https://cloud.githubusercontent.com/assets/1668207/8555313/3a9dc760-24bd-11e5-8106-9878e0631e80.png)

Here the  "since 1.0.2" is actually part of the variable $colors, but it looks like it belongs to "Variables".

Can we please add it inline with the variable/function name?

E.g. "Colors - since v1.0.2"

**Comment by pascalduez** [comment]
Thanks for reporting.

Moved to SassDoc/sassdoc-theme-default#79
