### ISSUE TITLE
Add ability to embed content

### ISSUE THREAD

**Issue by indrekpaas** [SassDoc/sassdoc#418]
I'm afraid this might be out of scope, but I'm thinking of a feature where I could embed external content (pens, gists, why not videos even) into the generated docs. 

I understand `@link` is meant for linking out to external resources, but having it embedded to the document creates more integrated experience, since the plain code examples are often not very straight-forward and having a live pen for reference would add a lot of value.

**Comment by pascalduez** [comment]
Hi,

I believe this might be an interesting addition. 
Most of the work (iframe formatting) would be handled by the theme or a new `sassdoc-extras` filter.

So core should provide a new annotation.

`@embed service <link>` ?

Base supported services: sassmeister, gist, codepen, jsbin, jsfiddle, dabblet, ... 

Just a quick though.

**Comment by HugoGiraudel** [comment]
I like the idea. Do you think we could use [Embedly](http://embed.ly/) perhaps?

**Comment by HugoGiraudel** [comment]
Not sure I still want this. Sounds overkill. Thoughts @SassDoc/owners?

**Comment by pascalduez** [comment]
Once again, a mix of [specific annotations](http://sassdoc.com/extending-sassdoc/) and a [custom theme](http://sassdoc.com/using-your-own-theme/) should do it, no need to add this to the core.

**Comment by HugoGiraudel** [comment]
This seems like a great case for custom annotations so I’m going to close this. :)
