### ISSUE TITLE
using with dependent gulp tasks

### ISSUE THREAD

**Issue by eoneill** [SassDoc/sassdoc#420]
First, SassDoc is awesome! Many thanks for making this!

I'm using sassdoc as part of a static site build that will be deployed to a gh-pages branch. The issue I'm running into is that sassdoc is asynchronous and I haven't found a hook that let's me know when it's "done done".

My gulp deploy task depends on the static site build and sassdoc:

```js
gulp.task("deploy", ["build", "sassdoc"], ...);
```

The problem is that `deploy` executes before `sassdoc` has completed.

I saw the note about the `end` event on [sassdoc.com/gulp](http://sassdoc.com/gulp), and tried using the promise, but that still didn't seem to guarantee that files are actually written to disk before yielding.

```js
gulp.task("sassdoc", function () {
  var stream = sassdoc({
    dest: "./dist/api"
  });

  gulp.src("sass/**/*.s[ac]ss")
    .pipe(stream);

  return stream.promise.then(function () {
    console.log(fs.readdirSync("./dist/api")); // nothing there :(
  });
});
```

I'm currently hacking around this by waiting...
```js
gulp.task("sassdoc", function () {
  return gulp.src("sass/**/*.s[ac]ss")
    .pipe(sassdoc({
      dest: "./dist/api"
    })
    .pipe(require("gulp-wait")(1000));
});
```

This is obviously very wrong :).

Is there a recommended way to integrate with dependent gulp tasks?

If not, could I recommend that `sassdoc()` take an option to only emit doneness after writing to disk?
```js
sassdoc({
  ...
  waitForDocumentize: true
})
```

**Comment by HugoGiraudel** [comment]
Hello.

```javascript
gulp.task("sassdoc", function () {
  var stream = sassdoc({ ... });

  gulp.src("sass/**/*.s[ac]ss")
    .pipe(stream);

  return stream.promise;
});
```

**Comment by eoneill** [comment]
D'oh. That was simple. Thanks Hugo!

**Comment by HugoGiraudel** [comment]
My pleasure, always. :)

**Comment by pascalduez** [comment]
Hey there, 

Both code examples are identical... And actually @eoneill one should work just fine.

The issue is not coming from the promise or stream, but rather the glob pattern: `sass/**/*.s[ac]ss` does not match anything. I would rather go with something like `sass/**/*.{sass,scss}`.
