### ISSUE TITLE
Add ability to have SassDoc snippets in Sublime Text

### ISSUE THREAD

**Issue by Stephn-R** [SassDoc/sassdoc#422]

**Comment by HugoGiraudel** [comment]
It's not really up to Sublime Text but to a Docblockr plugin such as: https://github.com/spadgos/sublime-jsdocs. So the best way to go would be to extend this plugin to make it work with SassDoc annotations. :)

**Comment by Stephn-R** [comment]
Sounds like a plan :) I am sure we can integrate with DocBlockr for that

**Comment by GitScrum** [comment]
+1

**Comment by pascalduez** [comment]
Dupe of #204

**Comment by HugoGiraudel** [comment]
Not on our side anyway.
