### ISSUE TITLE
TypeError: object is not a function when adding custom annotation

### ISSUE THREAD

**Issue by alademann** [SassDoc/sassdoc#425]
Hi there!

I'm trying to add a custom annotation to my theme.  However, I'm doing my best to follow the instructions on sassdoc.com, but I continue to get an error in the console: 

```
>> TypeError: object is not a function
```

Is there a more complete example of how to implement something like this?  This is what I've got in my theme's `index.js` file:

``` js
module.exports = function (dest, ctx) {
  // ... theme stuff ...
};

module.exports.annotations = [];

module.exports.annotations.push({
  name: 'awesome',
  parse: function () { return true; },
  default: function (comment) { return false; },
  autofill: function (comment) {},
  multiple: false,
  alias: ['wow'],
});
```

What am I missing?

**Comment by valeriangalliat** [comment]
Hey,

Each annotation is actually a function returning an object, see [`src/annotation/annotations`](https://github.com/SassDoc/sassdoc/tree/master/src/annotation/annotations) for an example of what you should provide.

So you just have to do the following:

```js
module.exports.annotations.push(function () {
  return {
    name: 'awesome',
    ...
  }
})
```

**Comment by timschoch** [comment]
It looks like the documentation needs to be update accordingly.
http://sassdoc.com/extending-sassdoc/

**Comment by valeriangalliat** [comment]
Indeed. Or we could support both, either a function or directly an object...

**Comment by HugoGiraudel** [comment]
The document seems to correctly reflect that so I am going to close this. Feel free to reopen if you think this deserves more work.
