### ISSUE TITLE
Can't get "parameter" annotation to work without error

### ISSUE THREAD

**Issue by smlombardi** [SassDoc/sassdoc#427]
The documentation for "Parameter" reads:
```
/// @param {type} $name
/// @param {type | othertype} $name
/// @param {type} $name - description
/// @param {type} $name [default value] - description
```
But I must not get it, since this throws a Gulp error:
[WARNING] Annotation `parameter` is not allowed on comment from type `unknown` in `_mixins.scss:184:184`.

```
/// HiDPI mixin. Default value set to 1.3 to target Google Nexus 7 (http://bjango.com/articles/min-device-pixel-ratio/)
@mixin hidpi($ratio: 1.3) {
  @media only screen and (-webkit-min-device-pixel-ratio: $ratio),
  only screen and (min--moz-device-pixel-ratio: $ratio),
  only screen and (-o-min-device-pixel-ratio: #{$ratio}/1),
  only screen and (min-resolution: round($ratio * 96dpi)),
  only screen and (min-resolution: $ratio * 1dppx) {
    @content;
  }
}
/// @param number $ratio
/// @example scss - Usage
// @include hidpi(1.5) {
//   --stuff
// }```

**Comment by pascalduez** [comment]
Hi,

all your doc comments and annotations needs to be grouped above the documented item. You can't split them as you did.

**Comment by smlombardi** [comment]
Can you please include a sample of how the annotations are used? I put them
all above, no more error but no params output either.

`@param {type} $name [default value] - description` is only partly helpful;
can you supply a sample is a use context?

For example, the Neat docs have params like
[image: Inline image 1]

What would be the corresponding sassdoc code used to generate this?

**Comment by pascalduez** [comment]
The neat code can be browsed here: https://github.com/thoughtbot/neat/blob/master/app/assets/stylesheets/

As for your first example:
```scss
/// HiDPI mixin. Default value set to 1.3 to target Google Nexus 7
/// @param {Number} $ratio [1.3] - A description
/// @example scss - Usage
///   @include hidpi(1.5) {
///      color: blue;
///    }
@mixin hidpi($ratio: 1.3) {
  ...
}
```

TIP 1: the indentation for the example is mandatory, since the example snippet is starting with an `@`.
TIP 2: You can play/test your comments online with http://sassdoc.com/sassdocmeister

**Comment by smlombardi** [comment]
Many thanks. I love sassdoc, excellent work.
