### ISSUE TITLE
Escaping characters?

### ISSUE THREAD

**Issue by smlombardi** [SassDoc/sassdoc#428]
I was trying to do this:
```
/// @example scss - Usage
/// @include breakpoint(screen-xs) {
///   .copyright {
///     font-size: 11px;
///   }
/// }
```

But the compiler choked on the @include.  I tried `\@` and it compiles but the `\` shows in the docs.

**Comment by pascalduez** [comment]
From http://sassdoc.com/annotations/#example

> Lines starting with @ need to be indented to work correctly.

So you need to:
```scss
/// @example scss - Usage
///   @include breakpoint(screen-xs) {
///     .copyright {
///       font-size: 11px;
///     }
///   }
```
