### ISSUE TITLE
Add ability to provide list of accepted values for @param

### ISSUE THREAD

**Issue by Undistraction** [SassDoc/sassdoc#432]
It would be great to be able to add a list of accepted values to an @param annotation, for example:

```
/// @param {String} $side [top] (top, right, bottom, left) Some example text
```

**Comment by HugoGiraudel** [comment]
I think this is the description’s job. I’m personally not in favour. @SassDoc/owners?

**Comment by valeriangalliat** [comment]
Agreed.

**Comment by pascalduez** [comment]
I like the idea to be able to have those values highlighted in a way, not mixed in the description.
Bu on the other hand a bit concerned about the complexity it adds to the `@param` grammar.

In a prefect world, authors would test for false param values and warn or error accordingly
So the `@throw` annotation could also be used here.

**Comment by HugoGiraudel** [comment]
@FWeinb Care to weigh in? I’d like to close, but not without your approval.

**Comment by HugoGiraudel** [comment]
15 months later, I’m quietly going to close this. We recommend using the description to convey this information. :)
