### ISSUE TITLE
Feature: Add originating file location to docs

### ISSUE THREAD

**Issue by Undistraction** [SassDoc/sassdoc#433]
In larger codebases (with the documented code spread across many files in a potentially complex directory tree), it would be nice to include the the project-relative location of the file containing the mixin / function, for example:

Location: `src/sass/config/typography.scss`

**Comment by pascalduez** [comment]
This is already provided by SassDoc, there's a `file` key per data item. 
It's then up to the theme whether to use it or not.  

Check SassDoc/sassdoc-theme-default#45

I think if your looking for full power over your docs and the ability to add new features, you should definitely look into [creating your own theme](http://sassdoc.com/using-your-own-theme/).

**Comment by Undistraction** [comment]
Fair enough. 

Thanks for the link.
