### ISSUE TITLE
Removing default groups name

### ISSUE THREAD

**Issue by seyedi** [SassDoc/sassdoc#434]
Hi thanks for the great job. Is there any way to stop sassdoc to categorize documnts into functions, mixins, placeholders, variables?

See, I want to see just my custom groups in the sidebar menu not mixin and ...

**Comment by HugoGiraudel** [comment]
Not with the defaulttheme unfortunately.

**Comment by pascalduez** [comment]
Solution: build a custom theme, don't use the `byGroupAndType` extras filter.

**Comment by seyedi** [comment]
@HugoGiraudel , @pascalduez Thanks a lot guys :+1:
