### ISSUE TITLE
Add visualization for Requires and Used by

### ISSUE THREAD

**Issue by timschoch** [SassDoc/sassdoc#435]
Navigating with the links that are generated for **requires** and **used by** is very handy for smaller projects. But with alot of variables it gets messy quickly. By integrating a Tree View (like http://bl.ocks.org/mbostock/4339083) this would be greatly enhanced.

This is our real world scenario:
We have a framework with a large set of specific variables that inherit their default value from more general ones. This makes it very fast to create basic stylings. eg Colors:

	// specific class inherits value from very general one
	(specific class) $topNavColor > $navColor > $linkColor > $corporateColor (general class)
Now there are branches, for example link states.

	$linkColorHover inherits from $corporateColorLight
	$linkColorSelected, $linkColorSelectedHover inherits from $linkColorHover

In reality there are even more layers, for example header or footer, which makes it very difficult to keep track of what the relationships between the variables across those branches are.

If something like this could be added, this would be great.
Maybe we could help you implement it, if you point me to where and how you would want something like this to be implemented.

**Comment by HugoGiraudel** [comment]
I don’t think this feature will ever be added in SassDoc’s core as it would probably be quite massive, but I could see a plugin that would use SassDoc to build a data tree like the one you linked to.

**Comment by timschoch** [comment]
I can understand that. Is there a ressource on creating a plugin?

**Comment by pascalduez** [comment]
Hi,

I guess with a mix of [specific annotations](http://sassdoc.com/extending-sassdoc/) and a [custom theme](http://sassdoc.com/using-your-own-theme/) one could go pretty far.

**Comment by timschoch** [comment]
Yep, I've looked through that page but did not find anything called a plugin - hence my question.

**Comment by HugoGiraudel** [comment]
Plugin was my generic word for “a tool built with SassDoc”. In this case, it could be a theme.

**Comment by timschoch** [comment]
Mkay, I'll have a look at it - thanks
