### ISSUE TITLE
Duplicated anchor links

### ISSUE THREAD

**Issue by michaelbazos** [SassDoc/sassdoc#436]
I have the following structure :

* **theme 1**
  * variables
    * primary-color
* **theme 2**
  * variables
    * primary-color

Generated links are:

* *#theme1*
  * *#theme1-variable*
    * *#variable-primary-color*
* *#theme2*
  * *#theme2-variable*
    * *#variable-primary-color*

As shown in the above list, items links generation do not take into account the heading group. As a consequence, theme-related variables have duplicated links.

**Comment by HugoGiraudel** [comment]
Oh. Damn. :(

**Comment by valeriangalliat** [comment]
@michaelbazos Hi, thanks for reporting. Would really appreciate a basic `.scss` file to reproduce this, or a link to the repo you have the bug with.

**Comment by michaelbazos** [comment]
Sure. The original repo is on a company-owned gitlab, but I've created a minimal example demonstrating the issue [in this repository](//github.com/michaelbazos/sassdoc-issue436).

Steps to reproduce the issue:
 1. clone the repository
 1. look existing or regenerated *sassdoc* folder

**Comment by pascalduez** [comment]
Moved to SassDoc/sassdoc-theme-default#83

**Comment by pascalduez** [comment]
Fixed as of `sassdoc-theme-default@2.4.1`
