### ISSUE TITLE
Build fails without further notice using Sassdoc v2.1.16 

### ISSUE THREAD

**Issue by timschoch** [SassDoc/sassdoc#438]
Hello Folks
We've upgraded to the latest sassdoc version and our builds fail without tellung us what's wrong. This is the only Info that gets logged:

	2015-11-30T10:09:40.7706789Z Executing the powershell script: D:\asdf\tasks\Gulp\0.5.4\Gulptask.ps1
	2015-11-30T10:09:41.0674204Z C:\Users\xyz\AppData\Roaming\npm\gulp.cmd copy sassdoc --gulpfile "d:\work\31\s\gulpfile.js" 
	2015-11-30T10:09:43.5362138Z [11:09:43] Using gulpfile d:\work\31\s\gulpfile.js
	2015-11-30T10:09:43.5362138Z [11:09:43] Starting 'clean'...
	2015-11-30T10:09:43.5518342Z [11:09:43] Starting 'lint'...
	2015-11-30T10:09:43.5518342Z [11:09:43] Finished 'lint' after 203 ╬╝s
	2015-11-30T10:09:43.5518342Z [11:09:43] Starting 'sassdoc'...

We tried to replicate the problem on a dev vm and locally, but no difference an no more infos.
It just stalls and doesn't report anything. With v2.1.15 it works fine.

Task config is:
````js
// Build the Core Sassdoc
gulp.task('sassdoc', function () {
	var options = {
			dest: 'Documentation/sassdoc',
			theme: './node_modules/sassdoc-theme-ioz', // <- same for default theme
			verbose: true,
			force: true
		};
	return gulp.src(path.join(paths.src, '/**/*.scss'))
    		.pipe(sassdoc(options));
});

**Comment by HugoGiraudel** [comment]
What is the last working version for you?

**Comment by timschoch** [comment]
v2.1.15

**Comment by HugoGiraudel** [comment]
Pinging @pascalduez. In the mean time, I suggest you lock down to 2.1.15.

**Comment by timschoch** [comment]
Already done. Any idea how we could get more debug information in the mean time?

**Comment by pascalduez** [comment]
Humm dang, the only change in the latest version is the `scss-comment-parser` bump.
Investigation time...

**Comment by pascalduez** [comment]
@timschoch Maybe you could try to generate the docs with just the SassDoc cli (no Gulp) and in such using the `--debug` option.

**Comment by timschoch** [comment]
This is all I get:

````
» [DEBUG] argv: ["./src/scss/**/*.scss","-d","Documentation/sassdoc","-v","--debug"]
» [DEBUG] process.argv: ["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\xyz\\AppData\\Roaming\\npm\\node_modules\\sassdoc\\bin\\sassdoc","./src/scss/**/*.scss","-d","Documentation/sassdoc","-v","--debug"]
» [DEBUG] sassdoc version: 2.1.16
» [DEBUG] node version: 4.2.2
» [DEBUG] npm version: unknown
» [DEBUG] platform: win32
» [DEBUG] cwd: D:\repos\BowerPackage.FirmendesignCore
» [DEBUG] env: {
	"_eventsCount": 2,
	"strict": false,
	"file": ".sassdocrc",
	"dest": "D:\\repos\\BowerPackage.FirmendesignCore\\Documentation\\sassdoc",
	"destCwd": true,
	"dir": "D:\\repos\\BowerPackage.FirmendesignCore",
	"displayDest": "Documentation\\sassdoc",
	"package": {
		"name": "ioz.firmendesignCore",
		"version": "0.1.0",
		"description": "IOZ Firmendesign Core - Bower Package",
		"main": "gulpfile.js",
		"author": {
			"name": "IOZ AG",
			"email": "info@ioz.ch",
			"url": "https://www.ioz.ch"
		},
		"license": "UNLICENSED",
		"keywords": [
			"ioz",
			"firmendesign"
		],
		"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"
		},
		"repository": {
			"type": "git",
			"url": "https://git.it/DefaultCollection/IOZ/_git/BowerPackage.FirmendesignCore"
		},
		"homepage": "https://git.it/DefaultCollection/IOZ/_welcome#name=BowerPackage.FirmendesignCore",
		"devDependencies": {
			"del": "^2.0.2",
			"gulp": "^3.9.0",
			"path": "^0.12.7",
			"sassdoc": "2.1.15",
			"sassdoc-theme-ioz": "^0.2.2"
		},
		"dependencies": {}
	},
	"displayTheme": "default",
	"themeName": "default",
	"src": [
		"./src/scss/**/*.scss"
	]
}
» [DEBUG] task: documentize

**Comment by valeriangalliat** [comment]
Temporarily fixed with 2.1.17, which is basically the same as using 2.1.15... (but at least won't affect new installs), see #439 for more info.

**Comment by HugoGiraudel** [comment]
Is this still happening in 2.1.20?

**Comment by pascalduez** [comment]
If I refer to #439 it should be fixed by now.
