### ISSUE TITLE
No package information

### ISSUE THREAD

**Issue by ryanmclaughlin** [SassDoc/sassdoc#441]
Hi there,

Trying to run `sassdoc stylesheets/` on my `.sass` files and I'm getting the following errors. Screenshot also has my `npm` and `sassdoc` version.

![2015-12-08 22 14 47](https://cloud.githubusercontent.com/assets/451112/11678072/48519976-9df9-11e5-8537-b194ff315aa2.png)

**Comment by pascalduez** [comment]
Hi,

the warning is a "normal" behaviour, it just means there's no `package.json` in your project or that you don't pass one through the config.

As for the Error, we'll need a bit more informations to be able to help. Can't you get a stackstrace ?
Also running SassDoc in verbose mode and debug mode.

You mention `.sass` files, are you using the indented syntax ?
In which case, is your stack following the [requirements](http://sassdoc.com/frequently-asked-questions/#does-sassdoc-work-with-sass-files) ?

**Comment by ryanmclaughlin** [comment]
Here's running with verbose and debug.

```
➜  mazlo-styleguide git:(master) sassdoc stylesheets/ --debug --verbose
» [DEBUG] argv: ["stylesheets/","--debug","--verbose"] 
» [WARNING] No package information.
» [DEBUG] process.argv: ["node","/usr/local/bin/sassdoc","stylesheets/","--debug","--verbose"] 
» [DEBUG] sassdoc version: 2.1.18 
» [DEBUG] node version: 0.10.21 
» [DEBUG] npm version: 2.5.0 
» [DEBUG] platform: darwin 
» [DEBUG] cwd: /Users/DeGrasse/Documents/Mazlo/mazlo-styleguide 
» [DEBUG] env: {
  "strict": false,
  "file": ".sassdocrc",
  "dir": "/Users/DeGrasse/Documents/Mazlo/mazlo-styleguide",
  "dest": "/Users/DeGrasse/Documents/Mazlo/mazlo-styleguide/sassdoc",
  "destCwd": true,
  "displayDest": "sassdoc",
  "package": {},
  "displayTheme": "default",
  "themeName": "default",
  "src": [
    "stylesheets/"
  ]
} 
» [DEBUG] task: documentize 
» [ERROR] [object Object]
```

As far as indented syntax `.sass`, yes I am, i.e.:

```sass
.button
  background-color: blue
```

sass-convert is installed as well.
```
➜  mazlo-styleguide git:(master) sass-convert -v
Sass 3.4.16 (Selective Steve)
```

**Comment by HugoGiraudel** [comment]
Is this still happening?
