### ISSUE TITLE
@!group directive

### ISSUE THREAD

**Issue by tf** [SassDoc/sassdoc#443]
I think it would be really handy if there was some sort of directive concept to apply an annotation to multiple elements at once. Especially defining groups can be quite repetitive. YARD solves this with the [@​group/@​endgroup](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#group) directives.

**Comment by pascalduez** [comment]
Hi,

you can achieve this with [file-level annotations](http://sassdoc.com/file-level-annotations).

**Comment by tf** [comment]
But there I can only define one group for all items, right? I think there can be cases where it can make sense to keep multiple groups in the same file.

**Comment by valeriangalliat** [comment]
Hmm, we would need CDocParser to support "range" annotations (with start and end markers), like for file-level annotations. Then updating CDocParser would automagically make SassDoc work with this syntax.

No even need to think about the `multiple` flag I guess, because it's exactly like a poster annotation in this regard.

I suggest to open this issue / make a PR on CDocParser. :+1:

**Comment by tf** [comment]
Interesting. @pascalduez comment made me wonder though if the urge to reach for group ranges is a smell in itself telling me to break apart my files. I'll watch out for this as I go along and open an issue with CDocParser when I have formed a clearer opinion. Thanks for the suggestion!

**Comment by pascalduez** [comment]
Re-opening to keep track of it, and get @SassDoc/owners feedback on this.

I'm not too keen at the moment, having several ways to perform certain actions might be confusing.

**Comment by HugoGiraudel** [comment]
Coming back to this, I’ll side with @pascalduez. That seems like unnecessary complexity?

**Comment by tf** [comment]
Agreed. Splitting things into multiple files is a good idea anyway. I think this, issue should be closed.

**Comment by pascalduez** [comment]
All right, let's close. 
We will need to planify a bit the future at some point, especially at the parser level.
