### ISSUE TITLE
Parser error when using the @argument annotation

### ISSUE THREAD

**Issue by tysongach** [SassDoc/sassdoc#444]
I’m getting an when parsing SassDoc comments with the `@argument` annotation.

The [SassDoc guides indicate that `@argument` is an alias for `@parameter`](http://sassdoc.com/annotations/#parameter). However, if I use `@argument` in place of `@parameter`, I get this error:

```bash
[WARNING] Parser for annotation `argument` not found. Location: `_size.scss:3:29`
```

Here’s the documentation that I’m parsing:

```scss
/// Sets the `width` and `height` of the element in one statement.
///
/// @argument {number} $width
///
/// @argument {number} $height [$width]
///
/// @example scss
/// .first-element {
///   @include size(2em);
/// }
///
/// .second-element {
///   @include size(auto, 10em);
/// }
///
/// @example css
/// .first-element {
///   width: 2em;
///   height: 2em;
/// }
///
/// .second-element {
///   width: auto;
///   height: 10em;
/// }
///
/// @require {function} is-size
```

To clarify, if I swap `@argument` for `@parameter`, it works and I _do not_ receive the warning. Even `@param` and `@arg` work just fine. It’s only when I use `@argument`, specifically.

**Comment by HugoGiraudel** [comment]
Apparently we made a typo in our alias and allowed `arguments` instead: https://github.com/SassDoc/sassdoc/blob/master/src/annotation/annotations/parameter.js#L33. We should fix that. Ping @SassDoc/owners?

**Comment by HugoGiraudel** [comment]
Created a PR to address that: https://github.com/SassDoc/sassdoc/pull/445.

**Comment by tysongach** [comment]
Oh, @HugoGiraudel, you’re so fast. Do you sleep? :smile: 

Thanks so much for your help, as always!

**Comment by HugoGiraudel** [comment]
Thank **you** for reporting this issue. I will wait for a review from owners and we’ll issue a patch. :)

**Comment by tysongach** [comment]
:+1:

**Comment by HugoGiraudel** [comment]
Version 2.1.20 released. Should fix your issue. :)

**Comment by tysongach** [comment]
Boom! Works like a charm.

Thanks @HugoGiraudel!

**Comment by HugoGiraudel** [comment]
You rock. :sparkles:

**Comment by pascalduez** [comment]
Thanks Hugo!

Which means we are lacking tests for aliases...
