### ISSUE TITLE
Switch to standard 

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc#447]
Maintaining our own ESLint config is quite tedious, it's moving fast, and we all kind of lack time.

What about switching to Standard ? Either with semi or without, I don't care.
I know we have already fervent users in the team, just opening an issue for good practices.

**Comment by HugoGiraudel** [comment]
Valérian will say standard. I’m fine with standard and semistandard. Ping @FWeinb?

**Comment by pascalduez** [comment]
We could also rather use the [config file](https://github.com/feross/eslint-config-standard) which would still give us a bit more control.

**Comment by valeriangalliat** [comment]
Huge YES for standard!

I'm also okay with semistandard, even extending the sharable config to tweak a couple settings, still better than maintaining our full own config.

**Comment by HugoGiraudel** [comment]
Did we ever do that? :D

**Comment by pascalduez** [comment]
We haven't done a damn thing :) 
I'm planning a heavy dependencies updates sessions, as well.

What about the [Airbnb config](https://www.npmjs.com/package/eslint-config-airbnb-base)? It's quite good.

**Comment by valeriangalliat** [comment]
I'm still totally for (semi)standard.

For dependencies https://david-dm.org/SassDoc/sassdoc can help

**Comment by pascalduez** [comment]
Done in #482 and merged on master.
