### ISSUE TITLE
add live example html view

### ISSUE THREAD

**Issue by omarazmi** [SassDoc/sassdoc#449]
add ability to add css & html code to demonstrate how to use the scss code, how it will looks like, and also how it will be used.

the @example annotation is not enough, we need the docs to be like bootstrap docs, but auto generated.

**Comment by pascalduez** [comment]
Hi,

that's already possible, but you will have to build your own theme to achieve this full behaviour.

A couple of examples: 
https://github.com/oddbird/sassdoc-theme-herman 
https://github.com/thoughtbot/sassdoc-theme-neat

**Comment by omarazmi** [comment]
thanks, i will review them.
