### ISSUE TITLE
SASSdoc with Gulp returns SassDoc could not find anything to document.

### ISSUE THREAD

**Issue by arkroy** [SassDoc/sassdoc#450]
Hi 

I'm trying to run SASSdoc 2.1.20 using a gulp task but it returns [WARNING] SassDoc could not find anything to document.

```js
gulp.task('sassdoc', function () {
    var stream = sassdoc(config.sassdocOptions)
    gulp.src(config.styles.in)
        .pipe(stream)
        return stream.promise;
});
````
Also tried:
```js
gulp.task('sassdoc', function () {
       return gulp
       .src(config.styles.in)
       .pipe(sassdoc(config.sassdocOptions));
});

gulp.task('build-prod', function(callback) {
    runSequence('sassdoc','jsdoc',['serve'],'size', callback);
});
gulp.task('build', ['build-prod']);
```
But works if I run:  sassdoc src/css --dest ./docs/sass/ directly on the terminal. Please could you help?

**Comment by pascalduez** [comment]
Hey,

could you show us the contents of `config.sassdocOptions` and `config.styles.in` ?
Or do you do have anything visible online ?

The structure of your Gulp tasks seems ok so far.

**Comment by arkroy** [comment]
Sorry about that. Please find below:

// SASS docs options
    sassdocOptions : {
            dest: './docs/sass/',
            display: {
                access: ['public'],
                watermark: false
            },
            groups: {
                fti: 'General',
                'undefined': 'Marketing Site'
            }
    },

**Comment by HugoGiraudel** [comment]
Is there any documented item in `./src/css/main.scss`?

**Comment by arkroy** [comment]
Yes, I get the HTML template files created the specified destination, but no documentation in it.

**Comment by HugoGiraudel** [comment]
That is not what I meant. Your source file is `./src/css/main.scss`. Did you document anything with SassDoc comments in there?

**Comment by arkroy** [comment]
No, there is no documentation in the main.scss file - I'm just using it for aggregation of thr partials. The documentation is in the partials being imported through the main.scss

**Comment by HugoGiraudel** [comment]
That’s the problem then. SassDoc does not follow imports.

**Comment by arkroy** [comment]
I tried putting in some documentation in main.scss, but it still doesn't solve the problem. Additionally, if I run the following directly through the terminal it works: 

sassdoc src/css --dest ./docs/sass/

So, I tried updating the gulp task such that it points to the directory and not just the file, but I'm getting the same error:

// SASS docs
    sassdoc: {
         in: './src/css/',
         options: {
                dest: './docs/sass/',
                display: {
                    access: ['public'],
                    watermark: false
                },
                groups: {
                    fti: 'group',
                    'undefined': 'Marketing Site'}
            }
    },...

gulp.task('sassdoc', function () {
    return gulp
        .src(config.sassdoc.in)
        .pipe(sassdoc(config.sassdoc.options));
});

**Comment by pascalduez** [comment]
You need to specify file extensions so that the globbing properly works.

http://sassdoc.com/gulp/ 
https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpsrcglobs-options  

Make a try with the following change : 
```js
sassdoc: {
  in: './src/css/**/*.scss', 
```

**Comment by arkroy** [comment]
Jeez, thanks it works now.. @pascalduez @HugoGiraudel.  I guess I can't point it to just the aggregation file.
