### ISSUE TITLE
search and links don't work with groups.

### ISSUE THREAD

**Issue by PeteJStewart** [SassDoc/sassdoc#451]
If you group your documentation, the search and body reference links stop working.
The links in the left hand menu still work as expected.

It seems that the search and the body links are simply not pre-pending the group name to the id reference.  for example, if you where to have a group call 'Breakpoints' and in there a variable called '$ex-small', the hash anchor in the side menu would be "#breakpoint-variable-ex-small" where as the search & reference link would be "#variable-ex-small"

I must admit I've been using sasdoc for a while and only just spotted this 6 legged feature.

**Comment by pascalduez** [comment]
Hi,

could you please provide more infos:
`sassdoc` version
`sassdoc-theme-default` version

**Comment by PeteJStewart** [comment]
sassdoc 2.1.17
As for the theme, it's whichever theme come as default with that version.
Let me know if you need more info.

**Comment by pascalduez** [comment]
Could you please try to re-install / udpate sassdoc, we are at `2.1.20` now, and there've been some recent fixes in the default theme regarding anchors and groups.

**Comment by HugoGiraudel** [comment]
Shall I close this?

**Comment by pascalduez** [comment]
I'm afraid we might still have that issue with the default theme, although it's been patched several times. Let's move the issue on that repo and do some testing.
