### ISSUE TITLE
options.exclude

### ISSUE THREAD

**Issue by robertmain** [SassDoc/sassdoc#453]
I can't honestly tell if this is a technical bug or a documentation bugs as (to my mind at least) there is a little ambiguity around the matter...

Using the gulp task provided in the example as a base, I wrote a gulp task that will run sassdoc over my sass files(see below):

```sass
gulp.task('app:generate:docs:sass', function(){
    return gulp.src('src/assets/src/styles/**/*.{css,scss}')
        .pipe(sassDoc({
            dest: './docs/sass',
            exclude: ['_shame.scss']
        }));
});
```

However, my issue comes with lin 6 where I am attempting to exclude _shame.scss ([see here](https://sass-guidelin.es/#shame-file) for more info) as I don't particularly want/need the details of the ugly CSS hacks I have had to do included in my nice pretty SASS API documentation....however, I can't seem to find a way to do this...

I have tried the following values for this field:

1. './_shame.scss'  
1. _'shame.scss'  
1. [ './_shame.scss']  
1. [ '_shame.scss']  
1. 'full/path/to/_shame.scss'  
1. './full/path/to/_shame.scss'  

All of which seems to have no effect. Does the `options.exclude` field exclude css also or does it just prevent sass from being parsed/documented?

I see this feature was being discussed in #228 but it looked (from the thread at least) to have been resolved

**Comment by pascalduez** [comment]
Hi,

the `exclude` option is only available for the CLI.
You've got to leverage Gulp's exclusion mechanism instead. (globbing patterns).

**Comment by robertmain** [comment]
Ah...I get you - that makes sense...

Perhaps a tweak to the docs might be in order then? Unless I just skimmed over that bit..

**Comment by pascalduez** [comment]
Your right, there's most probably things to improve in our docs.
