### ISSUE TITLE
Poster comment not parsed with '//' block

### ISSUE THREAD

**Issue by sgregson** [SassDoc/sassdoc#454]
Docs say 2+ slashes in between the poster comment delimiters is valid, but using two slashes doesn't parse/apply annotations properly.

This block fails to create a sassdoc entry for `$theme_purple` since the `@type` declaration is failing:
```scss
////
// My Variables File
// @group global
// @access private
// @type {color}
////

/// My special purple
$theme_purple: #969;
```

Personally, I would find actually using the two-slash comment useful, but I would understand if the resolution is changing the docs to indicate 3+ slashes 😢 

`sassdoc 2.1.20`, default themes (no configuration)

**Comment by HugoGiraudel** [comment]
I guess the docs are incorrect. Should be 3 slashes min. ;)

**Comment by sgregson** [comment]
rats :) legacy from prior parsing - I'll PR the docs when I get a spare minute.
