### ISSUE TITLE
Allow `@require` to reference third-party/external tools

### ISSUE THREAD

**Issue by mirisuzanne** [SassDoc/sassdoc#455]
Currently, both `@see` and `@require` expect local references to mixins/functions/variables that are also being documented in the same project. Only `@link` allows external references. Since `@see` and `@link` seem relatively equal in semantics, I don't think `@see` is a problem. But sometimes you do *require* external components, and using `@link` feels too weak.

**Comment by pascalduez** [comment]
Hi @mirisuzanne,

could you show us an example of what you're trying to acheive?
Basically `@require` allows for external references, in a variety of ways, either it be links or API like notations.

http://sassdoc.com/annotations/#require

`/// @require {type} item description <link>`

> Link is optional.
Item name can contain ::, :, . and/or / when item is from an external resource.
Link is used as a link if present, else it tries to link to an inner item, else it doesn’t have a link.

**Comment by mirisuzanne** [comment]
When we link an external reference like:

```scss
/// @require {function} size <http://oddbird.net/accoutrement-scale/sassdoc/sizes.html#function--size>
```

We get this error:

```bash
[WARNING] Item `corners` requires `size` from type `function` but this item doesn't exist.
```

oh! maybe we're just missing the `::`? I must have missed that in the docs.

**Comment by pascalduez** [comment]
The `:` or `::` shouldn't be mandatory.

I pasted your snippet in http://sassdoc.com/sassdocmeister/ and looks amlost good except the `external` key wich is set to false...

Let's investigate.

**Comment by HugoGiraudel** [comment]
Did you have the information you wanted @mirisuzanne? :)

**Comment by mirisuzanne** [comment]
I think so, thanks!
