### ISSUE TITLE
Windows Issue

### ISSUE THREAD

**Issue by JSteelBDML** [SassDoc/sassdoc#456]
I have been trying to run Sassdoc 2.1.20 inside Visual Studio 2015 on windows 7 with Node 6.1.2 installed and using Gulp. Unfortunately I get the following error trying to generate the docs:

» [ERROR] Error: Implement me. Unknown stdin file type!
[15:43:38] Finished 'sassdocs' after 212 ms
    at process.stdin (node.js:673:17)

I know there is nothing wrong with the tasks since the same code runs just fine on Mac OSX.

**Comment by valeriangalliat** [comment]
Looks like this is an implementation problem with Node itself https://github.com/nodejs/node/blob/f856234ffaa10441545c3b6ce420b247a17c06cf/lib/internal/process/stdio.js#L82

There's already an issue, but not much about it https://github.com/nodejs/help/issues/105

**Comment by JSteelBDML** [comment]
Yes I believe its a platform / node issue rather then Sassdoc itself, wondering if anyone knows a work around at all. I have the seen the issue come up with other plugins on windows, but nothing very concrete on how to resolve it.

**Comment by HugoGiraudel** [comment]
Is there anything we can do on our side to help?
