### ISSUE TITLE
How to document vendor code?

### ISSUE THREAD

**Issue by bendman** [SassDoc/sassdoc#459]
Is it possible to document vendor SCSS, and if so, how?

For example, if you use Bourbon or Susy in your Sass, how would document mixins provided by the vendor library, without adding comments to the vendor library itself?

Is there some way to add doc comments that are associated with an import, or aren't associated with any code?

**Comment by HugoGiraudel** [comment]
Hey there.

As of today, there is no way to do that. I’m sorry. :(

**Comment by pascalduez** [comment]
Hi,

Sounds a little bit weird isn't it? 
I would say it's not the responsibility of a given code to document its third party dependencies.  
On the other hand one can always leverage the `@require` annotation to explicitly define them.

**Comment by bendman** [comment]
@pascalduez Yeah, I think it's not really the responsibility of a styleguide to document third party tools like that, but it's an unfortunate reality if the tools don't have great docs, you have a particular way of using the tool, or you want documentation all in one place.

If we find a workaround we'll post it in here for others that might share our concerns though!

**Comment by HugoGiraudel** [comment]
I’m going to close this. :)
