### ISSUE TITLE
Limited Markdown in the description field

### ISSUE THREAD

**Issue by pete-hotchkiss** [SassDoc/sassdoc#463]
Am I correct that the MD parser that generated the markup based on the formatted comments in a .scss file only uses a subset of MD formatting.

I ask only in that I cant for example seem to be able to render tables.

Unless I'm missing summat?

**Comment by HugoGiraudel** [comment]
It uses [marked](https://github.com/chjj/marked) as you can view [here](https://github.com/SassDoc/sassdoc-extras/blob/master/src/markdown.js#L12).

**Comment by pete-hotchkiss** [comment]
OK that makes sense - figured if tables weren't there then it would be documented. 

Which means I'm doing something dumb

```
/// Here's the first part of my description. 
///   | key | Value |
///   |:--|:---|
///   | ```foo``` | 100 |
///   | ```bar``` | 200 |
```

**Comment by HugoGiraudel** [comment]
Can you make sure this Markdown sample can actually be compiled by Marked?

**Comment by HugoGiraudel** [comment]
I’m going to close this. :)
