### ISSUE TITLE
Bugs with inline comments 

### ISSUE THREAD

**Issue by airen** [SassDoc/sassdoc#466]
When using the new `///` sass comment format, at-rules in scss `@param` annotations choke. Parsing the block shown below produces this console output: **[WARNING] Annotation `parameter` is not allowed on comment from type `css` in `_burger.scss:17:53`**

```
/// @param {number} $width  30px
/// @param {number} $height  5px
/// @param {Number} $gutter  3px
/// @param {string} $color  #000
/// @param {number} $border-radius  0
/// @param {number} $transition-duration  0
```

https://github.com/w3cplus/SassMagic/blob/master/src/mixins/_burger.scss

who can help me fix the warning? Thanks!

**Comment by HugoGiraudel** [comment]
Could you remove this empty line (53): https://github.com/w3cplus/SassMagic/blob/master/src/mixins/_burger.scss#L53?

Tell me what happens.

**Comment by HugoGiraudel** [comment]
Shall I close this?
