### ISSUE TITLE
Alternative comments style

### ISSUE THREAD

**Issue by herzinger** [SassDoc/sassdoc#467]
Hi. I use, contribute to and am quite passionate about [inuitcss](https://github.com/inuitcss/inuitcss). 

It is heavily commented, but has almost no proper documentation apart from that, so something like sassdoc would be amazingly useful. That being said, it was ruled out by the core team members, the main reason being:

>The commenting style of SassDoc is a Sass comment, hence it doesn't get printed in the compiled CSS. We actually do want this to be the case, so we are using CSS comments where appropriate and Sass comments, where it must not be printed to the compiled CSS.
- [source](https://github.com/inuitcss/inuitcss/issues/164#issuecomment-249152342) 

Not only that, but they have a very particular set of guidelines for the commenting style.

Is there a way to work around this issue? And if not, can I have some advice on how to go about hacking this in a fork of my own?

**Comment by pascalduez** [comment]
Hi,

if you're fine with forks:

https://github.com/SassDoc/scss-comment-parser/blob/master/index.js#L191

```js
var extractor = new CDocParser.CommentExtractor(scssContextParser, { blockComment: false});
```
Change to:
```js
var extractor = new CDocParser.CommentExtractor(scssContextParser);
```

**Comment by herzinger** [comment]
@pascalduez thanks, I'll give it a try!

**Comment by HugoGiraudel** [comment]
I’m closing this. ;)
