### ISSUE TITLE
Theme annotation syntax

### ISSUE THREAD

**Issue by aputinski** [SassDoc/sassdoc#468]
Reviewing the docs, the custom theme annotation syntax is documented as:

```javascript
module.exports.annotations = [{
  name: 'foo',
  parse: t => t
}]
```

The above code was throwing errors for me, and after reviewing the source, it seems that annotations are expected to be functions?

https://github.com/SassDoc/sassdoc/blob/master/src/annotation/index.js#L41

The following code is currently working:

```javascript
module.exports.annotations = [
  () => ({
    name: 'foo',
    parse: t => t
  })
]
```

Am I missing something?

**Comment by HugoGiraudel** [comment]
Ping @valeriangalliat. :)

**Comment by pascalduez** [comment]
That's right, annotations are functions actualy. The documentation needs an update.

**Comment by HugoGiraudel** [comment]
Do you feel like you could PR the docs @aputinski? :)

**Comment by aputinski** [comment]
https://github.com/SassDoc/sassdoc.github.io/pull/141
