### ISSUE TITLE
Interpolation in selector wrongly parsed

### ISSUE THREAD

**Issue by davidknezic** [SassDoc/sassdoc#469]
I'm trying to document a couple of classes that have interpolation in the selectors using the latest sassdoc version:

```sass
/// Utility that makes your page (ex. body)
/// play nicely together with the side drawer. Use it
/// to pad your element to the left, so there's room for the drawer.
///
/// @example html - HTML Usage
///   <body class="push-lg-left">...</body>
.push-#{$breakpoint}-left {
  padding-left: $width;
}
```

What sassdoc does here is the following:

`comment.context.name` is `.push-#`
`comment.context.code` is `$breakpoint`

So it only parses this:

```sass
.push-#{$breakpoint}
```

It seems that it treats the curly braces as an indicator that `code` is coming, but it should ignore any `#{` and keep that as part of the selector.

**Comment by HugoGiraudel** [comment]
Could you try changing `.push` into `%push`? I want to try something.

**Comment by davidknezic** [comment]
Sure!

Interestingly, by using

```sass
%push-#{$breakpoint}-left {
  padding-left: $width;
}
```

... the docs turn into this:

`comment.context.name` is `push-`
`comment.context.code` is `padding-left: $width;`

**Comment by HugoGiraudel** [comment]
Code is good, at least.

Ping @SassDoc/owners.

**Comment by davidknezic** [comment]
Is it this part that should take care of my case?
https://github.com/SassDoc/scss-comment-parser/blob/master/index.js#L99

If so, I could try debugging this part.

**Comment by HugoGiraudel** [comment]
To be fair, I’m not entirely sure. :D

**Comment by davidknezic** [comment]
After a quick debugging session, this is the place where things start to go wrong:
https://github.com/SassDoc/scss-comment-parser/blob/master/index.js#L146

The `indexOf('{')` grabs the opening curly brace of the interpolation and not the one of the code block.

**Comment by davidknezic** [comment]
When I replace this line with `startIndex = findCodeStart(ctxCode, 0);` things work properly!

**Comment by HugoGiraudel** [comment]
Ideally, we would need @FWeinb to have a look.

**Comment by pascalduez** [comment]
Ideally we would switch all our parsing to postcss and postcss-scss at some point...

**Comment by HugoGiraudel** [comment]
Haha. :x

**Comment by FWeinb** [comment]
We should really think about postcss-scss at some point! But the PR on scss-comment-parser from @davidknezic looks good.
