### ISSUE TITLE
Issue with stream promise

### ISSUE THREAD

**Issue by arzafran** [SassDoc/sassdoc#472]
Hi all!, thanks in advance for taking the time to read and review this issue, hope some of you can help me with it.

This is my gulp task
```
gulp.task('doc', function() {
  var docstream = sassdoc(config.sassDocOptions);
  gulp.src(config.folderAssets.base + '/**/*.scss')
    .pipe(docstream);
    return docstream.promise.then(browserSync.reload());
});
```

The browsersync reloads, but the documentation is still generating, If I save any file again then it updates the server and works, but this two-step saving can generate issues when working with a large team.

Thanks in advance again!

Ps: Thanks to all who contributed to create sassdoc, this is a great library! :)

**Comment by pascalduez** [comment]
Hi,

the SassDoc part looks okay. I guess it's more about how you call the `reload` method, you invoke it, so it's executed right away.

What about:
```js
return docstream.promise.then(browserSync.reload);
````
or

```js
return docstream.promise.then(function () { browserSync.reload(); });
````

**Comment by arzafran** [comment]
nice catch!

`return docstream.promise.then(browserSync.reload);`

fixed it :) thanks!
