### ISSUE TITLE
Custom theme: sassdoc does not recompile with updated files

### ISSUE THREAD

**Issue by makabde** [SassDoc/sassdoc#473]
I am trying to build a custom theme for SassDoc and I am having an issue in my development workflow. 

Current code in branch https://github.com/makabde/sassdoc-theme-clear/tree/scaffold_layout

I use Gulp to watch the files, (re) compile and serve the files via BrowserSync. My issue is that whenever I modify a Swig file, Gulp will trigger a new flow to recompile the SassDoc theme. However, it seems that SassDoc has kept in memory the files used during the first compilation.

Any thoughts? I have been struggling with this for the last two days :(

**Comment by HugoGiraudel** [comment]
Hello,

That is a very odd issue. SassDoc doesn’t have a specific caching system (as we never really encountered performance issues). Maybe @pascalduez has an idea about this?

**Comment by pascalduez** [comment]
I tried to have a quick look but wihtout much luck. As Hugo already said there's no caching of any sort at SassDoc level. Swig as one though. 

A next step would be to try to debug in your repo.

**Comment by makabde** [comment]
@HugoGiraudel @pascalduez thanks for your answers.

I had a look at the Swig caching mechanism and it seems it was it. I am not sure the following hack is the good one but it solved my problem:

In my SassDoc theme `index.js` I added:
```js
  swig.setDefaults({ cache: false });
```
http://node-swig.github.io/swig-templates/docs/api/

**Comment by pascalduez** [comment]
Hey @makabde,

I think this is totally fine for development mode, although would not be needed for the released theme package. TBC.
I had a similar experience with Nunjucks. 
Somehow in Gulp, watch, Browsersync environment there's only one instance of the template engine created, hence hitting the cache. While in package mode, there should be one instance created on each run.

Glad you made it work.
