### ISSUE TITLE
How to document CSS classes?

### ISSUE THREAD

**Issue by delphinpro** [SassDoc/sassdoc#474]
How to can documented css classes?
I'm try so
```
/// Default link
.link {
  color: $link-color;
  text-decoration: none;

  /// Link to external resource
  &_external {
    &::after {
      @include materialIcons(0.7em);
    }
  }
}
```
The result is [http://s.delphinpro.ru/20161209-125540.png](http://s.delphinpro.ru/20161209-125540.png)
As you can see, there are no descriptions and something strange in the code (@css .link(){})
How to be? Is it possible to document the css classes?

**Comment by HugoGiraudel** [comment]
SassDoc does not ship a full blown Sass parser, meaning it won’t work with nesting.
