### ISSUE TITLE
Don't filter out comments with `type: unknown`

### ISSUE THREAD

**Issue by davisagli** [SassDoc/sassdoc#477]
In #84 it was decided to filter out comments with type: unknown so that /* */ style comments without any documentation would not be included in the parse result.

Now that only /// style comments are supported, would you accept a pull request to remove this filtering? In our theme we would like to use comments that are not attached to any context to include freeform prose in between documentation that is attached to Sass, but we can't currently do that because the sassdoc parser filters out the data here: https://github.com/SassDoc/sassdoc/blob/master/src/parser.js#L94

This would also help provide a solution to #460

**Comment by pascalduez** [comment]
This seems a legit evolution, I'm favorable to it.  
Not sure how this would be shipped semver wise. 

Ping @SassDoc/owners

**Comment by HugoGiraudel** [comment]
Hey. I think that’s a legit suggestion as well, but this would be a pretty breaking change I suppose.

**Comment by davisagli** [comment]
If it's a problem to introduce a breaking change, I could make it an option that is off by default.

**Comment by mirisuzanne** [comment]
I'd love to have this, so we can do a bit more "narrative" documentation on some of our Sass projects. Then I could Use SassDoc for the full Susy/True documentation.

**Comment by pascalduez** [comment]
Introduced as a "theme config key" in `sassdoc@2.3.0`
