### ISSUE TITLE
Why only Sass files?

### ISSUE THREAD

**Issue by Mihailoff** [SassDoc/sassdoc#494]
Your project is so awesome so I wonder why limit only to SAAS files and not parse annotations that are pretty much standard in many languages?!

**Comment by HugoGiraudel** [comment]
While in theory the parser could parse any file containing annotations described in the expected shape (three slashes + annotation dictionary), SassDoc is more than a parser. It is a generation builder. Also, SassDoc involves an actual Sass micro-parser, with syntax specific to Sass. Making this generic would be close to impossible.
