### ISSUE TITLE
group duplicate functions and mixins in requires and used by sections

### ISSUE THREAD

**Issue by chrisopedia** [SassDoc/sassdoc#507]
I've notice that if you have a function or mixin used more than once within a mixin, it shows up in the **Requires** and **Used by** sections.  Is it possible to just group those into 1 listing?

**Comment by pascalduez** [comment]
Hi,

somehow a dupe of #294.

**Comment by chrisopedia** [comment]
🤦‍♂️ sorry, somehow didn't find that one

**Comment by pascalduez** [comment]
@chrisopedia No worry !
