### ISSUE TITLE
Provide source file?

### ISSUE THREAD

**Issue by chrisopedia** [SassDoc/sassdoc#508]
As I'm building a custom theme, I noticed that the source lines come through the `ctx.data`, but I don't see any place where the actual file that is reference is located? Is it possible to provide the source file?

**Comment by chrisopedia** [comment]
Nevermind I found it in it the data

**Comment by pascalduez** [comment]
Hi @chrisopedia,

[sassdocmeister](http://sassdoc.com/sassdocmeister/) might comes handy while building a custom theme, to inspect the various data keys.

**Comment by chrisopedia** [comment]
@Pascalduez how do?

**Comment by pascalduez** [comment]
> How so?

Just a bit easier than printing json into a shell ;)

**Comment by chrisopedia** [comment]
Oh, I guess I misunderstood.
