### ISSUE TITLE
Could not find any executable for "sass-convert". Operation Aborted.

### ISSUE THREAD

**Issue by luisvillara** [SassDoc/sassdoc#522]
I'm trying to run `sassdoc <src>` and I'm getting this error:

`[ERROR] Could not find any executable for "sass-convert". Operation Aborted.`

<img width="642" alt="screen shot 2018-04-16 at 11 02 34 pm" src="https://user-images.githubusercontent.com/2540621/38848022-55b54e60-41ca-11e8-8f54-dd0ccc57abf9.png">

**Comment by pascalduez** [comment]
Hi,

please refer to the docs, you need to have Ruby Sass (hence sass-convert) installer either globaly or localy through bundler.
Also this is not an acceptable bug report, please provide OS, versions, node version, debugs etc.

**Comment by steffenpedersen** [comment]
Hi @luisvillara, did you get the project to run? If yes, then the issue can be closed 😃

**Comment by sabithpocker** [comment]
Refer docs [here](http://sassdoc.com/frequently-asked-questions/#does-sassdoc-work-with-sass-files)
