### ISSUE TITLE
Outdated changelog

### ISSUE THREAD

**Issue by robsonsobral** [SassDoc/sassdoc#523]
The last version on website changelog is 2.2.0, while the most recent available is 2.4.0. Can somebody rebuild the website?

Thank you.

**Comment by pascalduez** [comment]
Updated on the website as well. 


@steffenpedersen There's a task on the [website repo](https://github.com/SassDoc/sassdoc.github.io) named `make changelog` to update it.    
Sadly the current state of tasks in this repo is not great. But this one seems preserved :)
