### ISSUE TITLE
Question on Annotiations

### ISSUE THREAD

**Issue by pete-hotchkiss** [SassDoc/sassdoc#524]
Hiya,

I've been digging into the inner workings on sassdoc again; and I'm trying to figure out how the `display.annotiations` collection is populated. 

I'm specificlly interested to know how `display.annotations['variable']` is populated with the values 

```
description,type,property,require,example,usedby,since,see,link,author,todo
```

Any chance you can point me in the right direction ?

**Comment by pascalduez** [comment]
Hi,

it's coming from the [default theme](https://github.com/SassDoc/sassdoc-theme-default/blob/master/default.json).

**Comment by pete-hotchkiss** [comment]
there's me pooring into the inner workings of the renderer :-)

Thanks so much
