### ISSUE TITLE
Add the ability for offline networks

### ISSUE THREAD

**Issue by WebStew** [SassDoc/sassdoc#525]
Would it be possible to add the ability for the docs to not make a network request? Perhaps add an option to generate the documentation for an offline mode? We work in an offline environment and it takes a long time for the font and jQuery call to fail before the docs are rendered.

**Comment by pascalduez** [comment]
Hi,

that would be easy to do for sure, but not sure we want to bleat our config with a bunch of options.
One important thing to note, we really try to encourage users to build their own theme, the default theme can't satisfy any and every needs.

**Comment by WebStew** [comment]
I was just thinking of a custom theme to get round the problem. Thanks @pascalduez .

**Comment by t871088249** [comment]
> I was just thinking of a custom theme to get round the problem. Thanks @pascalduez .

Maybe you can change the cdn in your index.html at the bottom of the document

**Comment by pascalduez** [comment]
To go even further, we should just rewrite the default theme without jQuery.
