### ISSUE TITLE
Document which SASS items can be documented

### ISSUE THREAD

**Issue by dharkness** [SassDoc/sassdoc#526]
I've added file-level comments to a few files containing CSS rules, but they don't appear in the docs. I documented a mixin which did appear. So, what items will show up in the generated documentation once they are documented? Please list them on the Annotations page or somewhere more appropriate.

**Comment by pascalduez** [comment]
Hi, 

each item need at least one comment/title above it to be registered. File level comments are just a way to apply annotations to several items at once.

**Comment by dharkness** [comment]
I was unclear, sorry. Which of these items (once documented) will appear in the docs?

* variables - yes
* mixins - yes
* functions - ?
* selectors - no

I'd like to be able to comment selectors that are used as building blocks or are reused across the site. Is that possible?
