### ISSUE TITLE
latest sassdoc has vulnerability issues

### ISSUE THREAD

**Issue by rajkumar-mariselvaraj** [SassDoc/sassdoc#529]
Low             Regular Expression Denial of Service

  Package         uglify-js

  Patched in      >=2.6.0

  Dependency of   sassdoc

  Path            sassdoc > sassdoc-theme-default > swig > uglify-js

  More info       https://nodesecurity.io/advisories/48

**Comment by reneroth** [comment]
Pretty much a non-issue in this use case.

**Comment by pascalduez** [comment]
@reneroth See, I can also thumb up ;)

**Comment by pascalduez** [comment]
closing in favor of SassDoc/sassdoc-theme-default#96
