### ISSUE TITLE
Bug: Escaping in Class Names

### ISSUE THREAD

**Issue by reneroth** [SassDoc/sassdoc#531]
Using a class name like `.o-grid__cell.-w50\@small` - with the @ escaped for Sass reasons, resulting in a Class of `.o-grid__cell.-w50@small` - should output the class names without the escaping `\`.

Would this be best solved in the core or theme?

**Comment by pascalduez** [comment]
Hey,

most likely coming from [scss-comment-parser](https://github.com/SassDoc/scss-comment-parser).

**Comment by reneroth** [comment]
@pascalduez at which point should we adjust this? It'd make sense to output the class names the way they should be used in HTML, and not the way they need to be written in CSS. Should we provide the theme with the already de-escaped names, or do the de-escaping in the themes? Or do nothing at all about it?
