### ISSUE TITLE
"alias" suffix in the sidebar

### ISSUE THREAD

**Issue by kaelig** [SassDoc/sassdoc#536]
In https://github.com/sass-mq/sass-mq/pull/120, I updated to the latest version of SassDoc, and we're getting a sidebar looking like this:

![Screenshot_2019-05-07_23_29_04](https://user-images.githubusercontent.com/85783/57354361-1fec9000-7120-11e9-8125-996ca1bc45da.png)

Compare with the current version at https://sass-mq.github.io/sass-mq/

Is this a regression?

**Comment by renatodeleao** [comment]
Also getting this, needs some investigation as the condition seems right indeed.

**Comment by pascalduez** [comment]
Fixed in `sassdoc-theme-default@2.8.2`.
