### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by lipedeitos** [SassDoc/sassdoc#541]
There's anyway of outputting multiple files, one for each input ou maybe one per @group?
Can we just extract the sassdoc comments straight through html, without, the cleanest way possible, so we could put those files inside our own structure?
Finally, can we output markdown instead of html?

(I'v made a lot of research before posting this but the results are awful)

**Comment by pascalduez** [comment]
Hi,

just use SassDoc in "parse" mode and use of the data in any way you like.  

`sassdoc --parse` http://sassdoc.com/getting-started/#options  
`sassdoc.parse()` http://sassdoc.com/node/#using-raw-data   

Some built a Restructured text theme for instance: https://github.com/ellioseven/sassdoc-theme-rest
