### ISSUE TITLE
Regular Expression Denial of Service in 'marked' dependency before 0.7.0

### ISSUE THREAD

**Issue by laurelstreng** [SassDoc/sassdoc#543]
Greetings! I happened to run `npm audit` and ran into the following:
```
  Low             Regular Expression Denial of Service

  Package         marked

  Patched in      >=0.7.0

  Dependency of   sassdoc [dev] 

  Path            sassdoc > sassdoc-theme-default > sassdoc-extras > marked

  More info       https://npmjs.com/advisories/1076 
```
Looks like there's a new version 0.8.0 available for `marked`

**Comment by pascalduez** [comment]
Hi @laurelstreng,

thanks for reporting. Would you like to submit a PR to update it?

**Comment by laurelstreng** [comment]
@pascalduez  - Whoops, didn't realize it was for sassdoc-extras. Submitted a PR to sassdoc-extras https://github.com/SassDoc/sassdoc-extras/pull/43

**Comment by pascalduez** [comment]
`sassdoc-extras@3.0.0`.

We are not ready to tackle a breaking change here, so just upgrade `sassdoc-extras@3.0.0` locally.
