### ISSUE TITLE
Overrides the editor.definitionLinkOpensInPeek setting.

### ISSUE THREAD

**Issue by gmccullo** [SassDoc/sassdoc#574]
When the "Some Sass" extension is installed ctrl-clicking or "go to defiinition" on a mixin call always opens the peek pop-up, even when editor.definitionLinkOpensInPeek is set.

**Comment by gmccullo** [comment]
Sorry *not* "go to definition" or f12, just ctrl-click is affected.

**Comment by pascalduez** [comment]
Hello,

could you please be a bit more descriptive and precise in describing your issue?
At first glance looks like you opened it on the wrong repository.

**Comment by gmccullo** [comment]
> Hello,
> 
> could you please be a bit more descriptive and precise in describing your issue?
> At first glance looks like you opened it on the wrong repository. 
> 
> 

I don't know what else to say about it. What question did you have?

What is the right repository?

**Comment by pascalduez** [comment]
Here you are on the SassDoc repository, I invite you to check it and figure what it does and what not.

In this project there's no such things as:
- "Some Sass" extension 
- editor.definitionLinkOpensInPeek

So your sentence makes absolutely no sense in this context. 

More generally, if you don't take the time to describe precisely your issue, giving context, information, reproduction, links, data etc. to help maintainers eventually help you, you won't get any help. You have to make more efforts.
