### ISSUE TITLE
Default theme: item group is not included in item name link

### ISSUE THREAD

**Issue by jdgarvey** [SassDoc/sassdoc#575]
The "group" value for an item does not get inserted into the item's link.
This means that clicking on an item's name h3 results in the wrong anchor string, so the page does not jump to that item and deep linking to that item doesn't work.

The sidebar and search result links correctly prepend the group to the link.

Example
Given the following sass
```sass
/// @group helpers
.foobar {display: none;}
```
the h3 for .foobar will contain `<a class="item__name" href="#css-.foobar">`.
This is incorrect, it should be `<a class="item__name" href="#helpers-css-.foobar">`.

I have a PR to fix this, posting here for more visibility.
https://github.com/SassDoc/sassdoc-theme-default/pull/118

**Comment by pascalduez** [comment]
Fix published as of `sassdoc-theme-default@2.8.6`.
