### ISSUE TITLE
Shouldn't parse @import

### ISSUE THREAD

**Issue by KittyGiraudel** [SassDoc/sassdoc#73]
I've finally understood the issue we have when running SassDoc on `view/scss`: because some `@import` directives directly follow a C-style comment, they get parsed.

``` scss
/**
 * Partials
 */
@import "partials/header";
```

This should not happen.

**Comment by liaoyongfu** [comment]
Why do I @import "a.scss" in the SCSS file, but "a.scss" will not be documented?

**Comment by pascalduez** [comment]
> Why do I @import "a.scss" in the SCSS file, but "a.scss" will not be documented?

SassDoc won't resolve and import Sass `@import` statements, it's not its role.

To document several files use the [source argument](http://sassdoc.com/getting-started/#sassdoc-command):

> `<src>` is the path to one or more Sass folders or glob expressions to SCSS/Sass files

**Comment by liaoyongfu** [comment]
@pascalduez , Thanks very much!
